// ============================================================================
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated by scripts/build-flutter.js
// Edit the source at src/data/colors.js and run: npm run build:flutter
// ============================================================================

/// Candi Color Palette for Flutter
///
/// A Scandinavian-inspired color palette based on Nordic design principles:
/// Hygge (warmth) and Lagom (balance).
///
/// ## Quick Start
///
/// ```dart
/// import 'package:candi_colors/candi.dart';
///
/// // Access colors directly
/// Container(color: CandiColors.light.surface);
///
/// // Use convenience aliases
/// Text('Hello', style: TextStyle(color: CandiColors.dark.muted));
///
/// // Create a ThemeData
/// MaterialApp(theme: CandiColors.light.toThemeData());
/// ```
///
/// Generated from OKLCH source of truth.
/// Total colors: 123 per palette
library;

import 'package:flutter/material.dart';

/// A [Color] implementation that retains OKLCH metadata.
///
/// OKLCH is a perceptually uniform color space that provides better
/// color manipulation and contrast calculations than traditional RGB.
///
/// ## Properties
///
/// - [lightness]: Perceived lightness (0.0 = black, 1.0 = white)
/// - [chroma]: Color intensity (0.0 = gray, higher = more saturated)
/// - [hue]: Color angle in degrees (0-360)
/// - [candiOpacity]: Alpha channel (0.0 = transparent, 1.0 = opaque)
///
/// ## Example
///
/// ```dart
/// final accent = CandiColors.light.accent;
/// print(accent.lightness); // 0.52
/// print(accent.chroma);    // 0.06
/// print(accent.hue);       // 230.0
/// ```
class CandiColor extends Color {
  /// Perceived lightness in OKLCH (0.0-1.0).
  final double lightness;

  /// Color intensity/saturation in OKLCH.
  final double chroma;

  /// Hue angle in degrees (0-360).
  final double hue;

  /// Opacity/alpha value (0.0-1.0).
  final double candiOpacity;

  /// Creates a [CandiColor] with OKLCH metadata.
  const CandiColor(
    int value, {
    required this.lightness,
    required this.chroma,
    required this.hue,
    this.candiOpacity = 1.0,
  }) : super(value);

  @override
  String toString() =>
      'CandiColor(oklch(${(lightness * 100).toStringAsFixed(0)}% $chroma $hue))';
}

/// Semantic color palette for the Candi theme.
///
/// Provides a complete set of colors for building UIs with consistent
/// visual hierarchy and accessibility.
///
/// ## Color Categories
///
/// - **Backgrounds**: [bg], [surface], [elevated]
/// - **Text**: [text], [textSubtle], [textMuted]
/// - **Borders**: [border], [borderStrong], [divider]
/// - **Accent**: [accent], [accentSubtle], [onAccent]
/// - **Secondary**: [secondary], [secondarySubtle], [onSecondary]
/// - **Status**: [success], [warning], [error], [info] (with `on*` variants)
/// - **Interactive**: [link], [disabled], [focusRing], [hover], [active]
/// - **Overlays**: [overlay], [scrim], [shadowColor]
/// - **Inverse**: [inverseSurface], [inverseText]
///
/// ## Convenience Aliases
///
/// Common naming patterns from other design systems:
/// - [muted] → [textMuted]
/// - [subtle] → [textSubtle]
/// - [primary] → [accent]
/// - [onPrimary] → [onAccent]
class CandiPalette {
  const CandiPalette._({
    required this.bg,
    required this.surface,
    required this.elevated,
    required this.text,
    required this.textSubtle,
    required this.textMuted,
    required this.border,
    required this.borderStrong,
    required this.divider,
    required this.accent,
    required this.accentSubtle,
    required this.accentSoft,
    required this.accentStrong,
    required this.accentOutline,
    required this.onAccent,
    required this.secondary,
    required this.secondarySubtle,
    required this.secondarySoft,
    required this.secondaryStrong,
    required this.secondaryOutline,
    required this.onSecondary,
    required this.success,
    required this.successSubtle,
    required this.successSoft,
    required this.successStrong,
    required this.successOutline,
    required this.onSuccess,
    required this.warning,
    required this.warningSubtle,
    required this.warningSoft,
    required this.warningStrong,
    required this.warningOutline,
    required this.onWarning,
    required this.error,
    required this.errorSubtle,
    required this.errorSoft,
    required this.errorStrong,
    required this.errorOutline,
    required this.onError,
    required this.info,
    required this.infoSubtle,
    required this.infoSoft,
    required this.infoStrong,
    required this.infoOutline,
    required this.onInfo,
    required this.link,
    required this.disabled,
    required this.focusRing,
    required this.overlay,
    required this.scrim,
    required this.shadowColor,
    required this.inverseSurface,
    required this.inverseText,
    required this.hover,
    required this.active,
    required this.terminalBlack,
    required this.terminalRed,
    required this.terminalGreen,
    required this.terminalYellow,
    required this.terminalBlue,
    required this.terminalMagenta,
    required this.terminalCyan,
    required this.terminalWhite,
    required this.red,
    required this.redSubtle,
    required this.redSoft,
    required this.redStrong,
    required this.redOutline,
    required this.onRed,
    required this.blue,
    required this.blueSubtle,
    required this.blueSoft,
    required this.blueStrong,
    required this.blueOutline,
    required this.onBlue,
    required this.green,
    required this.greenSubtle,
    required this.greenSoft,
    required this.greenStrong,
    required this.greenOutline,
    required this.onGreen,
    required this.yellow,
    required this.yellowSubtle,
    required this.yellowSoft,
    required this.yellowStrong,
    required this.yellowOutline,
    required this.onYellow,
    required this.magenta,
    required this.magentaSubtle,
    required this.magentaSoft,
    required this.magentaStrong,
    required this.magentaOutline,
    required this.onMagenta,
    required this.cyan,
    required this.cyanSubtle,
    required this.cyanSoft,
    required this.cyanStrong,
    required this.cyanOutline,
    required this.onCyan,
    required this.teal,
    required this.tealSubtle,
    required this.tealSoft,
    required this.tealStrong,
    required this.tealOutline,
    required this.onTeal,
    required this.pink,
    required this.pinkSubtle,
    required this.pinkSoft,
    required this.pinkStrong,
    required this.pinkOutline,
    required this.onPink,
    required this.gold,
    required this.goldSubtle,
    required this.goldSoft,
    required this.goldStrong,
    required this.goldOutline,
    required this.onGold,
    required this.silver,
    required this.silverSubtle,
    required this.silverSoft,
    required this.silverStrong,
    required this.silverOutline,
    required this.onSilver,
  });

  /// Page background color.
  final CandiColor bg;

  /// Card and section background color.
  final CandiColor surface;

  /// Elevated surface (modals, popups) background color.
  final CandiColor elevated;

  /// Primary text color.
  final CandiColor text;

  /// Secondary/subdued text color.
  final CandiColor textSubtle;

  /// Tertiary/muted text color for less important content.
  final CandiColor textMuted;

  /// Default border color.
  final CandiColor border;

  /// Emphasized border color.
  final CandiColor borderStrong;

  /// Divider/separator line color.
  final CandiColor divider;

  /// Primary accent color for buttons and interactive elements.
  final CandiColor accent;

  /// Subtle accent for hover states and backgrounds.
  final CandiColor accentSubtle;

  /// The accentSoft color.
  final CandiColor accentSoft;

  /// The accentStrong color.
  final CandiColor accentStrong;

  /// The accentOutline color.
  final CandiColor accentOutline;

  /// Text color on accent backgrounds.
  final CandiColor onAccent;

  /// Secondary action color (terracotta).
  final CandiColor secondary;

  /// Subtle secondary for backgrounds.
  final CandiColor secondarySubtle;

  /// The secondarySoft color.
  final CandiColor secondarySoft;

  /// The secondaryStrong color.
  final CandiColor secondaryStrong;

  /// The secondaryOutline color.
  final CandiColor secondaryOutline;

  /// Text color on secondary backgrounds.
  final CandiColor onSecondary;

  /// Success state color (green).
  final CandiColor success;

  /// The successSubtle color.
  final CandiColor successSubtle;

  /// The successSoft color.
  final CandiColor successSoft;

  /// The successStrong color.
  final CandiColor successStrong;

  /// The successOutline color.
  final CandiColor successOutline;

  /// Text color on success backgrounds.
  final CandiColor onSuccess;

  /// Warning state color (amber).
  final CandiColor warning;

  /// The warningSubtle color.
  final CandiColor warningSubtle;

  /// The warningSoft color.
  final CandiColor warningSoft;

  /// The warningStrong color.
  final CandiColor warningStrong;

  /// The warningOutline color.
  final CandiColor warningOutline;

  /// Text color on warning backgrounds.
  final CandiColor onWarning;

  /// Error state color (coral red).
  final CandiColor error;

  /// The errorSubtle color.
  final CandiColor errorSubtle;

  /// The errorSoft color.
  final CandiColor errorSoft;

  /// The errorStrong color.
  final CandiColor errorStrong;

  /// The errorOutline color.
  final CandiColor errorOutline;

  /// Text color on error backgrounds.
  final CandiColor onError;

  /// Informational state color (blue).
  final CandiColor info;

  /// The infoSubtle color.
  final CandiColor infoSubtle;

  /// The infoSoft color.
  final CandiColor infoSoft;

  /// The infoStrong color.
  final CandiColor infoStrong;

  /// The infoOutline color.
  final CandiColor infoOutline;

  /// Text color on info backgrounds.
  final CandiColor onInfo;

  /// Hyperlink color.
  final CandiColor link;

  /// Disabled element color.
  final CandiColor disabled;

  /// Focus ring/outline color with opacity.
  final CandiColor focusRing;

  /// Overlay color for modals (semi-transparent).
  final CandiColor overlay;

  /// Scrim color for dimming backgrounds.
  final CandiColor scrim;

  /// Shadow color with transparency.
  final CandiColor shadowColor;

  /// Inverse surface for contrast elements.
  final CandiColor inverseSurface;

  /// Text color on inverse surfaces.
  final CandiColor inverseText;

  /// Hover state overlay color.
  final CandiColor hover;

  /// Active/pressed state overlay color.
  final CandiColor active;

  /// Terminal ANSI black color.
  final CandiColor terminalBlack;

  /// Terminal ANSI red color.
  final CandiColor terminalRed;

  /// Terminal ANSI green color.
  final CandiColor terminalGreen;

  /// Terminal ANSI yellow color.
  final CandiColor terminalYellow;

  /// Terminal ANSI blue color.
  final CandiColor terminalBlue;

  /// Terminal ANSI magenta color.
  final CandiColor terminalMagenta;

  /// Terminal ANSI cyan color.
  final CandiColor terminalCyan;

  /// Terminal ANSI white color.
  final CandiColor terminalWhite;

  /// Primitive red color.
  final CandiColor red;

  /// Subtle red background tint.
  final CandiColor redSubtle;

  /// Soft red foreground.
  final CandiColor redSoft;

  /// Strong/dark red variant.
  final CandiColor redStrong;

  /// Red outline/border color.
  final CandiColor redOutline;

  /// Text color on red backgrounds.
  final CandiColor onRed;

  /// Primitive blue color.
  final CandiColor blue;

  /// Subtle blue background tint.
  final CandiColor blueSubtle;

  /// Soft blue foreground.
  final CandiColor blueSoft;

  /// Strong/dark blue variant.
  final CandiColor blueStrong;

  /// Blue outline/border color.
  final CandiColor blueOutline;

  /// Text color on blue backgrounds.
  final CandiColor onBlue;

  /// Primitive green color.
  final CandiColor green;

  /// Subtle green background tint.
  final CandiColor greenSubtle;

  /// Soft green foreground.
  final CandiColor greenSoft;

  /// Strong/dark green variant.
  final CandiColor greenStrong;

  /// Green outline/border color.
  final CandiColor greenOutline;

  /// Text color on green backgrounds.
  final CandiColor onGreen;

  /// Primitive yellow color.
  final CandiColor yellow;

  /// Subtle yellow background tint.
  final CandiColor yellowSubtle;

  /// Soft yellow foreground.
  final CandiColor yellowSoft;

  /// Strong/dark yellow variant.
  final CandiColor yellowStrong;

  /// Yellow outline/border color.
  final CandiColor yellowOutline;

  /// Text color on yellow backgrounds.
  final CandiColor onYellow;

  /// Primitive magenta color.
  final CandiColor magenta;

  /// Subtle magenta background tint.
  final CandiColor magentaSubtle;

  /// Soft magenta foreground.
  final CandiColor magentaSoft;

  /// Strong/dark magenta variant.
  final CandiColor magentaStrong;

  /// Magenta outline/border color.
  final CandiColor magentaOutline;

  /// Text color on magenta backgrounds.
  final CandiColor onMagenta;

  /// Primitive cyan color.
  final CandiColor cyan;

  /// Subtle cyan background tint.
  final CandiColor cyanSubtle;

  /// Soft cyan foreground.
  final CandiColor cyanSoft;

  /// Strong/dark cyan variant.
  final CandiColor cyanStrong;

  /// Cyan outline/border color.
  final CandiColor cyanOutline;

  /// Text color on cyan backgrounds.
  final CandiColor onCyan;

  /// Primitive teal color.
  final CandiColor teal;

  /// Subtle teal background tint.
  final CandiColor tealSubtle;

  /// Soft teal foreground.
  final CandiColor tealSoft;

  /// Strong/dark teal variant.
  final CandiColor tealStrong;

  /// Teal outline/border color.
  final CandiColor tealOutline;

  /// Text color on teal backgrounds.
  final CandiColor onTeal;

  /// Primitive pink color.
  final CandiColor pink;

  /// Subtle pink background tint.
  final CandiColor pinkSubtle;

  /// Soft pink foreground.
  final CandiColor pinkSoft;

  /// Strong/dark pink variant.
  final CandiColor pinkStrong;

  /// Pink outline/border color.
  final CandiColor pinkOutline;

  /// Text color on pink backgrounds.
  final CandiColor onPink;

  /// Primitive gold color.
  final CandiColor gold;

  /// Subtle gold background tint.
  final CandiColor goldSubtle;

  /// Soft gold foreground.
  final CandiColor goldSoft;

  /// Strong/dark gold variant.
  final CandiColor goldStrong;

  /// Gold outline/border color.
  final CandiColor goldOutline;

  /// Text color on gold backgrounds.
  final CandiColor onGold;

  /// Primitive silver color.
  final CandiColor silver;

  /// Subtle silver background tint.
  final CandiColor silverSubtle;

  /// Soft silver foreground.
  final CandiColor silverSoft;

  /// Strong/dark silver variant.
  final CandiColor silverStrong;

  /// Silver outline/border color.
  final CandiColor silverOutline;

  /// Text color on silver backgrounds.
  final CandiColor onSilver;

  // ─────────────────────────────────────────────────────────────────────────
  // Convenience Aliases
  // ─────────────────────────────────────────────────────────────────────────

  /// Alias for [textMuted]. Common in design systems.
  CandiColor get muted => textMuted;

  /// Alias for [textSubtle]. Common in design systems.
  CandiColor get subtle => textSubtle;

  /// Alias for [accent]. Maps to Material's primary concept.
  CandiColor get primary => accent;

  /// Alias for [accentSubtle]. Subtle primary variant.
  CandiColor get primarySubtle => accentSubtle;

  /// Alias for [onAccent]. Text on primary backgrounds.
  CandiColor get onPrimary => onAccent;

  /// Alias for [bg]. Alternative naming convention.
  CandiColor get background => bg;

  // ─────────────────────────────────────────────────────────────────────────
  // Flutter Integration
  // ─────────────────────────────────────────────────────────────────────────

  /// Creates a [ColorScheme] from this palette.
  ///
  /// Maps Candi semantic colors to Material 3 color roles.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final scheme = CandiColors.light.toColorScheme();
  /// ThemeData(colorScheme: scheme);
  /// ```
  ColorScheme toColorScheme({Brightness? brightness}) {
    final isDark = bg.lightness < 0.5;
    return ColorScheme(
      brightness: brightness ?? (isDark ? Brightness.dark : Brightness.light),
      primary: accent,
      onPrimary: onAccent,
      primaryContainer: accentSubtle,
      onPrimaryContainer: text,
      secondary: secondary,
      onSecondary: onSecondary,
      secondaryContainer: secondarySubtle,
      onSecondaryContainer: text,
      tertiary: info,
      onTertiary: onInfo,
      tertiaryContainer: infoSubtle,
      onTertiaryContainer: text,
      error: error,
      onError: onError,
      errorContainer: errorSubtle,
      onErrorContainer: text,
      surface: surface,
      onSurface: text,
      onSurfaceVariant: textSubtle,
      outline: border,
      outlineVariant: borderStrong,
      shadow: shadowColor,
      scrim: scrim,
      inverseSurface: inverseSurface,
      onInverseSurface: inverseText,
      inversePrimary: accent,
      surfaceTint: accent,
    );
  }

  /// Creates a complete [ThemeData] from this palette.
  ///
  /// Provides a ready-to-use Material 3 theme with Candi colors.
  ///
  /// ## Example
  ///
  /// ```dart
  /// MaterialApp(
  ///   theme: CandiColors.light.toThemeData(),
  ///   darkTheme: CandiColors.dark.toThemeData(),
  /// );
  /// ```
  ///
  /// ## Parameters
  ///
  /// - [useMaterial3]: Use Material 3 design (default: true)
  ThemeData toThemeData({
    bool useMaterial3 = true,
  }) {
    final colorScheme = toColorScheme();
    return ThemeData(
      useMaterial3: useMaterial3,
      colorScheme: colorScheme,
      scaffoldBackgroundColor: bg,
      canvasColor: surface,
      cardColor: surface,
      dividerColor: divider,
      disabledColor: disabled,
      hoverColor: hover,
      focusColor: focusRing,
      highlightColor: active,
      splashColor: active,
      shadowColor: shadowColor,
      appBarTheme: AppBarTheme(
        backgroundColor: surface,
        foregroundColor: text,
        elevation: 0,
        surfaceTintColor: Colors.transparent,
      ),
      cardTheme: CardThemeData(
        color: surface,
        elevation: 1,
        shadowColor: shadowColor,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
        ),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: accent,
          foregroundColor: onAccent,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          foregroundColor: accent,
          side: BorderSide(color: border),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          foregroundColor: accent,
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: surface,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: BorderSide(color: border),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: BorderSide(color: border),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: BorderSide(color: accent, width: 2),
        ),
      ),
      dividerTheme: DividerThemeData(
        color: divider,
        thickness: 1,
      ),
      iconTheme: IconThemeData(
        color: textSubtle,
      ),
      textTheme: TextTheme(
        displayLarge: TextStyle(color: text),
        displayMedium: TextStyle(color: text),
        displaySmall: TextStyle(color: text),
        headlineLarge: TextStyle(color: text),
        headlineMedium: TextStyle(color: text),
        headlineSmall: TextStyle(color: text),
        titleLarge: TextStyle(color: text),
        titleMedium: TextStyle(color: text),
        titleSmall: TextStyle(color: text),
        bodyLarge: TextStyle(color: text),
        bodyMedium: TextStyle(color: text),
        bodySmall: TextStyle(color: textSubtle),
        labelLarge: TextStyle(color: text),
        labelMedium: TextStyle(color: textSubtle),
        labelSmall: TextStyle(color: textMuted),
      ),
    );
  }
}

/// Static access to light and dark Candi palettes.
///
/// ## Usage
///
/// ```dart
/// // Direct color access
/// Container(color: CandiColors.light.surface);
/// Text('Hello', style: TextStyle(color: CandiColors.dark.text));
///
/// // With theme
/// MaterialApp(
///   theme: CandiColors.light.toThemeData(),
///   darkTheme: CandiColors.dark.toThemeData(),
/// );
/// ```
abstract final class CandiColors {
  /// Light mode palette with warm, Nordic-inspired colors.
  ///
  /// Optimized for readability with WCAG AA contrast ratios.
  static const light = CandiPalette._(
    // oklch(97.5% 0.005 80)
    bg: CandiColor(0XFFF8F6F3, lightness: 0.975, chroma: 0.005, hue: 80),
    // oklch(95% 0.008 80)
    surface: CandiColor(0XFFF1EEE9, lightness: 0.95, chroma: 0.008, hue: 80),
    // oklch(99.5% 0.003 80)
    elevated: CandiColor(0XFFFEFDFB, lightness: 0.995, chroma: 0.003, hue: 80),
    // oklch(15% 0.01 80)
    text: CandiColor(0XFF0D0B07, lightness: 0.15, chroma: 0.01, hue: 80),
    // oklch(40% 0.008 80)
    textSubtle: CandiColor(0XFF4A4743, lightness: 0.4, chroma: 0.008, hue: 80),
    // oklch(52% 0.006 80)
    textMuted: CandiColor(0XFF6B6965, lightness: 0.52, chroma: 0.006, hue: 80),
    // oklch(84% 0.005 80)
    border: CandiColor(0XFFCCCAC7, lightness: 0.84, chroma: 0.005, hue: 80),
    // oklch(77% 0.006 80)
    borderStrong: CandiColor(
      0XFFB6B4B0,
      lightness: 0.77,
      chroma: 0.006,
      hue: 80,
    ),
    // oklch(90% 0.004 80)
    divider: CandiColor(0XFFDFDEDB, lightness: 0.9, chroma: 0.004, hue: 80),
    // oklch(50% 0.13 245)
    accent: CandiColor(0XFF0068A7, lightness: 0.5, chroma: 0.13, hue: 245),
    // oklch(83% 0.078 245)
    accentSubtle: CandiColor(
      0XFF9DCDF7,
      lightness: 0.83,
      chroma: 0.078,
      hue: 245,
    ),
    // oklch(60% 0.104 245)
    accentSoft: CandiColor(0XFF4586BA, lightness: 0.6, chroma: 0.104, hue: 245),
    // oklch(40% 0.143 245)
    accentStrong: CandiColor(
      0XFF004A8E,
      lightness: 0.4,
      chroma: 0.143,
      hue: 245,
    ),
    // oklch(35% 0.091 245)
    accentOutline: CandiColor(
      0XFF003E66,
      lightness: 0.35,
      chroma: 0.091,
      hue: 245,
    ),
    // oklch(100% 0 0)
    onAccent: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(55% 0.12 20)
    secondary: CandiColor(0XFFAC5154, lightness: 0.55, chroma: 0.12, hue: 20),
    // oklch(88% 0.072 20)
    secondarySubtle: CandiColor(
      0XFFFFC5C4,
      lightness: 0.88,
      chroma: 0.072,
      hue: 20,
    ),
    // oklch(65% 0.096 20)
    secondarySoft: CandiColor(
      0XFFC37777,
      lightness: 0.65,
      chroma: 0.096,
      hue: 20,
    ),
    // oklch(45% 0.132 20)
    secondaryStrong: CandiColor(
      0XFF902E35,
      lightness: 0.45,
      chroma: 0.132,
      hue: 20,
    ),
    // oklch(40% 0.084 20)
    secondaryOutline: CandiColor(
      0XFF6E3334,
      lightness: 0.4,
      chroma: 0.084,
      hue: 20,
    ),
    // oklch(100% 0 0)
    onSecondary: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(50% 0.10 150)
    success: CandiColor(0XFF337344, lightness: 0.5, chroma: 0.1, hue: 150),
    // oklch(83% 0.06 150)
    successSubtle: CandiColor(
      0XFFACD3B3,
      lightness: 0.83,
      chroma: 0.06,
      hue: 150,
    ),
    // oklch(60% 0.08 150)
    successSoft: CandiColor(0XFF5C8E67, lightness: 0.6, chroma: 0.08, hue: 150),
    // oklch(40% 0.11 150)
    successStrong: CandiColor(
      0XFF005725,
      lightness: 0.4,
      chroma: 0.11,
      hue: 150,
    ),
    // oklch(35% 0.07 150)
    successOutline: CandiColor(
      0XFF1B4526,
      lightness: 0.35,
      chroma: 0.07,
      hue: 150,
    ),
    // oklch(100% 0 0)
    onSuccess: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(60% 0.13 80)
    warning: CandiColor(0XFFA87600, lightness: 0.6, chroma: 0.13, hue: 80),
    // oklch(93% 0.078 80)
    warningSubtle: CandiColor(
      0XFFFFE3AD,
      lightness: 0.93,
      chroma: 0.078,
      hue: 80,
    ),
    // oklch(70% 0.104 80)
    warningSoft: CandiColor(0XFFC0974E, lightness: 0.7, chroma: 0.104, hue: 80),
    // oklch(50% 0.143 80)
    warningStrong: CandiColor(
      0XFF8D5600,
      lightness: 0.5,
      chroma: 0.143,
      hue: 80,
    ),
    // oklch(45% 0.091 80)
    warningOutline: CandiColor(
      0XFF6F4F05,
      lightness: 0.45,
      chroma: 0.091,
      hue: 80,
    ),
    // oklch(0% 0 0)
    onWarning: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(50% 0.14 25)
    error: CandiColor(0XFFA43B38, lightness: 0.5, chroma: 0.14, hue: 25),
    // oklch(83% 0.084 25)
    errorSubtle: CandiColor(
      0XFFF9B2AC,
      lightness: 0.83,
      chroma: 0.084,
      hue: 25,
    ),
    // oklch(60% 0.112 25)
    errorSoft: CandiColor(0XFFBA635E, lightness: 0.6, chroma: 0.112, hue: 25),
    // oklch(40% 0.154 25)
    errorStrong: CandiColor(0XFF880C17, lightness: 0.4, chroma: 0.154, hue: 25),
    // oklch(35% 0.098 25)
    errorOutline: CandiColor(
      0XFF64211F,
      lightness: 0.35,
      chroma: 0.098,
      hue: 25,
    ),
    // oklch(100% 0 0)
    onError: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(50% 0.10 225)
    info: CandiColor(0XFF006E8E, lightness: 0.5, chroma: 0.1, hue: 225),
    // oklch(83% 0.06 225)
    infoSubtle: CandiColor(0XFF9ED0E5, lightness: 0.83, chroma: 0.06, hue: 225),
    // oklch(60% 0.08 225)
    infoSoft: CandiColor(0XFF458AA4, lightness: 0.6, chroma: 0.08, hue: 225),
    // oklch(40% 0.11 225)
    infoStrong: CandiColor(0XFF005274, lightness: 0.4, chroma: 0.11, hue: 225),
    // oklch(35% 0.07 225)
    infoOutline: CandiColor(
      0XFF004256,
      lightness: 0.35,
      chroma: 0.07,
      hue: 225,
    ),
    // oklch(100% 0 0)
    onInfo: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(48% 0.14 240)
    link: CandiColor(0XFF0064A3, lightness: 0.48, chroma: 0.14, hue: 240),
    // oklch(82% 0.004 80)
    disabled: CandiColor(0XFFC5C4C1, lightness: 0.82, chroma: 0.004, hue: 80),
    // oklch(52% 0.06 240 / 0.4)
    focusRing: CandiColor(
      0X66486E88,
      lightness: 0.52,
      chroma: 0.06,
      hue: 240,
      candiOpacity: 0.4,
    ),
    // oklch(0% 0 0 / 0.5)
    overlay: CandiColor(
      0X80000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.5,
    ),
    // oklch(0% 0 0 / 0.32)
    scrim: CandiColor(
      0X52000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.32,
    ),
    // oklch(25% 0.005 80 / 0.15)
    shadowColor: CandiColor(
      0X2623211F,
      lightness: 0.25,
      chroma: 0.005,
      hue: 80,
      candiOpacity: 0.15,
    ),
    // oklch(25% 0.005 80)
    inverseSurface: CandiColor(
      0XFF23211F,
      lightness: 0.25,
      chroma: 0.005,
      hue: 80,
    ),
    // oklch(92% 0.005 80)
    inverseText: CandiColor(
      0XFFE6E4E1,
      lightness: 0.92,
      chroma: 0.005,
      hue: 80,
    ),
    // oklch(0% 0 0 / 0.05)
    hover: CandiColor(
      0X0D000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.05,
    ),
    // oklch(0% 0 0 / 0.1)
    active: CandiColor(
      0X1A000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.1,
    ),
    // oklch(25% 0.005 80)
    terminalBlack: CandiColor(
      0XFF23211F,
      lightness: 0.25,
      chroma: 0.005,
      hue: 80,
    ),
    // oklch(58% 0.12 25)
    terminalRed: CandiColor(0XFFB75B55, lightness: 0.58, chroma: 0.12, hue: 25),
    // oklch(52% 0.08 145)
    terminalGreen: CandiColor(
      0XFF4A754C,
      lightness: 0.52,
      chroma: 0.08,
      hue: 145,
    ),
    // oklch(68% 0.13 70)
    terminalYellow: CandiColor(
      0XFFCB882E,
      lightness: 0.68,
      chroma: 0.13,
      hue: 70,
    ),
    // oklch(52% 0.06 230)
    terminalBlue: CandiColor(
      0XFF437085,
      lightness: 0.52,
      chroma: 0.06,
      hue: 230,
    ),
    // oklch(60% 0.15 0)
    terminalMagenta: CandiColor(
      0XFFC5547C,
      lightness: 0.6,
      chroma: 0.15,
      hue: 0,
    ),
    // oklch(65% 0.1 200)
    terminalCyan: CandiColor(
      0XFF2BA1A7,
      lightness: 0.65,
      chroma: 0.1,
      hue: 200,
    ),
    // oklch(92% 0.01 85)
    terminalWhite: CandiColor(
      0XFFE8E4DD,
      lightness: 0.92,
      chroma: 0.01,
      hue: 85,
    ),
    // oklch(55% 0.14 25)
    red: CandiColor(0XFFB54A46, lightness: 0.55, chroma: 0.14, hue: 25),
    // oklch(88% 0.11 25)
    redSubtle: CandiColor(0XFFFFBBB3, lightness: 0.88, chroma: 0.11, hue: 25),
    // oklch(65% 0.13 25)
    redSoft: CandiColor(0XFFD36C66, lightness: 0.65, chroma: 0.13, hue: 25),
    // oklch(45% 0.15 25)
    redStrong: CandiColor(0XFF972527, lightness: 0.45, chroma: 0.15, hue: 25),
    // oklch(40% 0.13 25)
    redOutline: CandiColor(0XFF7F2021, lightness: 0.4, chroma: 0.13, hue: 25),
    // oklch(100% 0 0)
    onRed: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(50% 0.12 250)
    blue: CandiColor(0XFF2266A4, lightness: 0.5, chroma: 0.12, hue: 250),
    // oklch(83% 0.10 250)
    blueSubtle: CandiColor(0XFF95CDFF, lightness: 0.83, chroma: 0.1, hue: 250),
    // oklch(60% 0.11 250)
    blueSoft: CandiColor(0XFF4984BF, lightness: 0.6, chroma: 0.11, hue: 250),
    // oklch(40% 0.13 250)
    blueStrong: CandiColor(0XFF00488A, lightness: 0.4, chroma: 0.13, hue: 250),
    // oklch(35% 0.11 250)
    blueOutline: CandiColor(
      0XFF003B71,
      lightness: 0.35,
      chroma: 0.11,
      hue: 250,
    ),
    // oklch(100% 0 0)
    onBlue: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(55% 0.12 145)
    green: CandiColor(0XFF3E8343, lightness: 0.55, chroma: 0.12, hue: 145),
    // oklch(88% 0.10 145)
    greenSubtle: CandiColor(0XFFAEE9AF, lightness: 0.88, chroma: 0.1, hue: 145),
    // oklch(65% 0.11 145)
    greenSoft: CandiColor(0XFF62A164, lightness: 0.65, chroma: 0.11, hue: 145),
    // oklch(45% 0.13 145)
    greenStrong: CandiColor(
      0XFF146720,
      lightness: 0.45,
      chroma: 0.13,
      hue: 145,
    ),
    // oklch(40% 0.11 145)
    greenOutline: CandiColor(
      0XFF15561D,
      lightness: 0.4,
      chroma: 0.11,
      hue: 145,
    ),
    // oklch(100% 0 0)
    onGreen: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(75% 0.14 90)
    yellow: CandiColor(0XFFD0A92D, lightness: 0.75, chroma: 0.14, hue: 90),
    // oklch(95% 0.11 90)
    yellowSubtle: CandiColor(
      0XFFFFEC96,
      lightness: 0.95,
      chroma: 0.11,
      hue: 90,
    ),
    // oklch(82% 0.13 90)
    yellowSoft: CandiColor(0XFFE5C057, lightness: 0.82, chroma: 0.13, hue: 90),
    // oklch(65% 0.15 90)
    yellowStrong: CandiColor(
      0XFFB38900,
      lightness: 0.65,
      chroma: 0.15,
      hue: 90,
    ),
    // oklch(60% 0.13 90)
    yellowOutline: CandiColor(
      0XFF9E7B00,
      lightness: 0.6,
      chroma: 0.13,
      hue: 90,
    ),
    // oklch(0% 0 0)
    onYellow: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(55% 0.18 330)
    magenta: CandiColor(0XFFA840A2, lightness: 0.55, chroma: 0.18, hue: 330),
    // oklch(88% 0.14 330)
    magentaSubtle: CandiColor(
      0XFFFFB5FF,
      lightness: 0.88,
      chroma: 0.14,
      hue: 330,
    ),
    // oklch(65% 0.16 330)
    magentaSoft: CandiColor(
      0XFFC467BD,
      lightness: 0.65,
      chroma: 0.16,
      hue: 330,
    ),
    // oklch(45% 0.20 330)
    magentaStrong: CandiColor(
      0XFF8C0888,
      lightness: 0.45,
      chroma: 0.2,
      hue: 330,
    ),
    // oklch(40% 0.16 330)
    magentaOutline: CandiColor(
      0XFF73176F,
      lightness: 0.4,
      chroma: 0.16,
      hue: 330,
    ),
    // oklch(100% 0 0)
    onMagenta: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(65% 0.10 200)
    cyan: CandiColor(0XFF2BA1A7, lightness: 0.65, chroma: 0.1, hue: 200),
    // oklch(90% 0.08 200)
    cyanSubtle: CandiColor(0XFF9DEFF3, lightness: 0.9, chroma: 0.08, hue: 200),
    // oklch(72% 0.09 200)
    cyanSoft: CandiColor(0XFF56B6BB, lightness: 0.72, chroma: 0.09, hue: 200),
    // oklch(55% 0.11 200)
    cyanStrong: CandiColor(0XFF00848B, lightness: 0.55, chroma: 0.11, hue: 200),
    // oklch(50% 0.09 200)
    cyanOutline: CandiColor(0XFF007277, lightness: 0.5, chroma: 0.09, hue: 200),
    // oklch(0% 0 0)
    onCyan: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(55% 0.10 175)
    teal: CandiColor(0XFF11846E, lightness: 0.55, chroma: 0.1, hue: 175),
    // oklch(88% 0.08 175)
    tealSubtle: CandiColor(0XFF9EE9D4, lightness: 0.88, chroma: 0.08, hue: 175),
    // oklch(65% 0.09 175)
    tealSoft: CandiColor(0XFF4BA18C, lightness: 0.65, chroma: 0.09, hue: 175),
    // oklch(45% 0.11 175)
    tealStrong: CandiColor(0XFF006852, lightness: 0.45, chroma: 0.11, hue: 175),
    // oklch(40% 0.09 175)
    tealOutline: CandiColor(0XFF005745, lightness: 0.4, chroma: 0.09, hue: 175),
    // oklch(100% 0 0)
    onTeal: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(70% 0.12 0)
    pink: CandiColor(0XFFDA7D9B, lightness: 0.7, chroma: 0.12, hue: 0),
    // oklch(92% 0.10 0)
    pinkSubtle: CandiColor(0XFFFFC9E2, lightness: 0.92, chroma: 0.1, hue: 0),
    // oklch(78% 0.11 0)
    pinkSoft: CandiColor(0XFFF199B4, lightness: 0.78, chroma: 0.11, hue: 0),
    // oklch(60% 0.13 0)
    pinkStrong: CandiColor(0XFFBD5B7D, lightness: 0.6, chroma: 0.13, hue: 0),
    // oklch(55% 0.11 0)
    pinkOutline: CandiColor(0XFFA4546F, lightness: 0.55, chroma: 0.11, hue: 0),
    // oklch(0% 0 0)
    onPink: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(70% 0.12 70)
    gold: CandiColor(0XFFCE9042, lightness: 0.7, chroma: 0.12, hue: 70),
    // oklch(92% 0.10 70)
    goldSubtle: CandiColor(0XFFFFD99B, lightness: 0.92, chroma: 0.1, hue: 70),
    // oklch(78% 0.11 70)
    goldSoft: CandiColor(0XFFE5AB66, lightness: 0.78, chroma: 0.11, hue: 70),
    // oklch(60% 0.13 70)
    goldStrong: CandiColor(0XFFB17000, lightness: 0.6, chroma: 0.13, hue: 70),
    // oklch(55% 0.11 70)
    goldOutline: CandiColor(0XFF9A6418, lightness: 0.55, chroma: 0.11, hue: 70),
    // oklch(0% 0 0)
    onGold: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(75% 0.01 250)
    silver: CandiColor(0XFFA9AFB4, lightness: 0.75, chroma: 0.01, hue: 250),
    // oklch(92% 0.008 250)
    silverSubtle: CandiColor(
      0XFFE1E5EA,
      lightness: 0.92,
      chroma: 0.008,
      hue: 250,
    ),
    // oklch(82% 0.009 250)
    silverSoft: CandiColor(
      0XFFC0C5CA,
      lightness: 0.82,
      chroma: 0.009,
      hue: 250,
    ),
    // oklch(65% 0.012 250)
    silverStrong: CandiColor(
      0XFF8A9096,
      lightness: 0.65,
      chroma: 0.012,
      hue: 250,
    ),
    // oklch(60% 0.009 250)
    silverOutline: CandiColor(
      0XFF7C8185,
      lightness: 0.6,
      chroma: 0.009,
      hue: 250,
    ),
    // oklch(0% 0 0)
    onSilver: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
  );

  /// Dark mode palette with cool, muted tones.
  ///
  /// Maintains visual consistency with the light theme while
  /// reducing eye strain in low-light environments.
  static const dark = CandiPalette._(
    // oklch(20% 0.005 80)
    bg: CandiColor(0XFF171614, lightness: 0.2, chroma: 0.005, hue: 80),
    // oklch(26% 0.005 80)
    surface: CandiColor(0XFF252421, lightness: 0.26, chroma: 0.005, hue: 80),
    // oklch(32% 0.006 80)
    elevated: CandiColor(0XFF34332F, lightness: 0.32, chroma: 0.006, hue: 80),
    // oklch(90% 0.005 80)
    text: CandiColor(0XFFE0DEDA, lightness: 0.9, chroma: 0.005, hue: 80),
    // oklch(70% 0.005 80)
    textSubtle: CandiColor(0XFFA09E9B, lightness: 0.7, chroma: 0.005, hue: 80),
    // oklch(60% 0.004 80)
    textMuted: CandiColor(0XFF81807D, lightness: 0.6, chroma: 0.004, hue: 80),
    // oklch(40% 0.005 80)
    border: CandiColor(0XFF494745, lightness: 0.4, chroma: 0.005, hue: 80),
    // oklch(45% 0.006 80)
    borderStrong: CandiColor(
      0XFF575552,
      lightness: 0.45,
      chroma: 0.006,
      hue: 80,
    ),
    // oklch(35% 0.004 80)
    divider: CandiColor(0XFF3C3A38, lightness: 0.35, chroma: 0.004, hue: 80),
    // oklch(72% 0.12 245)
    accent: CandiColor(0XFF5EACEB, lightness: 0.72, chroma: 0.12, hue: 245),
    // oklch(45% 0.072 245)
    accentSubtle: CandiColor(
      0XFF30597B,
      lightness: 0.45,
      chroma: 0.072,
      hue: 245,
    ),
    // oklch(82% 0.096 245)
    accentSoft: CandiColor(
      0XFF8ECBFF,
      lightness: 0.82,
      chroma: 0.096,
      hue: 245,
    ),
    // oklch(62% 0.132 245)
    accentStrong: CandiColor(
      0XFF328DD0,
      lightness: 0.62,
      chroma: 0.132,
      hue: 245,
    ),
    // oklch(57% 0.084 245)
    accentOutline: CandiColor(
      0XFF4A7CA6,
      lightness: 0.57,
      chroma: 0.084,
      hue: 245,
    ),
    // oklch(0% 0 0)
    onAccent: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(75% 0.11 20)
    secondary: CandiColor(0XFFEB9191, lightness: 0.75, chroma: 0.11, hue: 20),
    // oklch(48% 0.066 20)
    secondarySubtle: CandiColor(
      0XFF7F4E4E,
      lightness: 0.48,
      chroma: 0.066,
      hue: 20,
    ),
    // oklch(85% 0.088 20)
    secondarySoft: CandiColor(
      0XFFFFB7B6,
      lightness: 0.85,
      chroma: 0.088,
      hue: 20,
    ),
    // oklch(65% 0.121 20)
    secondaryStrong: CandiColor(
      0XFFCF6F70,
      lightness: 0.65,
      chroma: 0.121,
      hue: 20,
    ),
    // oklch(60% 0.077 20)
    secondaryOutline: CandiColor(
      0XFFAA6D6D,
      lightness: 0.6,
      chroma: 0.077,
      hue: 20,
    ),
    // oklch(0% 0 0)
    onSecondary: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(78% 0.10 150)
    success: CandiColor(0XFF88CA95, lightness: 0.78, chroma: 0.1, hue: 150),
    // oklch(51% 0.06 150)
    successSubtle: CandiColor(
      0XFF4D7054,
      lightness: 0.51,
      chroma: 0.06,
      hue: 150,
    ),
    // oklch(88% 0.08 150)
    successSoft: CandiColor(
      0XFFB2E7BC,
      lightness: 0.88,
      chroma: 0.08,
      hue: 150,
    ),
    // oklch(68% 0.11 150)
    successStrong: CandiColor(
      0XFF63AB74,
      lightness: 0.68,
      chroma: 0.11,
      hue: 150,
    ),
    // oklch(63% 0.07 150)
    successOutline: CandiColor(
      0XFF6A9573,
      lightness: 0.63,
      chroma: 0.07,
      hue: 150,
    ),
    // oklch(0% 0 0)
    onSuccess: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(82% 0.12 80)
    warning: CandiColor(0XFFEDBB64, lightness: 0.82, chroma: 0.12, hue: 80),
    // oklch(55% 0.072 80)
    warningSubtle: CandiColor(
      0XFF886D3F,
      lightness: 0.55,
      chroma: 0.072,
      hue: 80,
    ),
    // oklch(92% 0.096 80)
    warningSoft: CandiColor(
      0XFFFFDE9A,
      lightness: 0.92,
      chroma: 0.096,
      hue: 80,
    ),
    // oklch(72% 0.132 80)
    warningStrong: CandiColor(
      0XFFD09A32,
      lightness: 0.72,
      chroma: 0.132,
      hue: 80,
    ),
    // oklch(67% 0.084 80)
    warningOutline: CandiColor(
      0XFFB09057,
      lightness: 0.67,
      chroma: 0.084,
      hue: 80,
    ),
    // oklch(0% 0 0)
    onWarning: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(78% 0.12 25)
    error: CandiColor(0XFFFB9890, lightness: 0.78, chroma: 0.12, hue: 25),
    // oklch(51% 0.072 25)
    errorSubtle: CandiColor(
      0XFF8B5551,
      lightness: 0.51,
      chroma: 0.072,
      hue: 25,
    ),
    // oklch(88% 0.096 25)
    errorSoft: CandiColor(0XFFFFBFB8, lightness: 0.88, chroma: 0.096, hue: 25),
    // oklch(68% 0.132 25)
    errorStrong: CandiColor(
      0XFFDE756E,
      lightness: 0.68,
      chroma: 0.132,
      hue: 25,
    ),
    // oklch(63% 0.084 25)
    errorOutline: CandiColor(
      0XFFB7756F,
      lightness: 0.63,
      chroma: 0.084,
      hue: 25,
    ),
    // oklch(0% 0 0)
    onError: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(78% 0.10 225)
    info: CandiColor(0XFF6AC5E8, lightness: 0.78, chroma: 0.1, hue: 225),
    // oklch(51% 0.06 225)
    infoSubtle: CandiColor(0XFF3D6E80, lightness: 0.51, chroma: 0.06, hue: 225),
    // oklch(88% 0.08 225)
    infoSoft: CandiColor(0XFF9DE3FF, lightness: 0.88, chroma: 0.08, hue: 225),
    // oklch(68% 0.11 225)
    infoStrong: CandiColor(0XFF3AA6CB, lightness: 0.68, chroma: 0.11, hue: 225),
    // oklch(63% 0.07 225)
    infoOutline: CandiColor(
      0XFF5892A9,
      lightness: 0.63,
      chroma: 0.07,
      hue: 225,
    ),
    // oklch(0% 0 0)
    onInfo: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(65% 0.14 240)
    link: CandiColor(0XFF2098DB, lightness: 0.65, chroma: 0.14, hue: 240),
    // oklch(45% 0.004 80)
    disabled: CandiColor(0XFF565553, lightness: 0.45, chroma: 0.004, hue: 80),
    // oklch(62% 0.08 80 / 0.5)
    focusRing: CandiColor(
      0X80A0814C,
      lightness: 0.62,
      chroma: 0.08,
      hue: 80,
      candiOpacity: 0.5,
    ),
    // oklch(0% 0 0 / 0.7)
    overlay: CandiColor(
      0XB3000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.7,
    ),
    // oklch(0% 0 0 / 0.6)
    scrim: CandiColor(
      0X99000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.6,
    ),
    // oklch(0% 0 0 / 0.4)
    shadowColor: CandiColor(
      0X66000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.4,
    ),
    // oklch(92% 0.005 80)
    inverseSurface: CandiColor(
      0XFFE6E4E1,
      lightness: 0.92,
      chroma: 0.005,
      hue: 80,
    ),
    // oklch(20% 0.005 80)
    inverseText: CandiColor(0XFF171614, lightness: 0.2, chroma: 0.005, hue: 80),
    // oklch(100% 0 0 / 0.1)
    hover: CandiColor(
      0X1AFFFFFF,
      lightness: 1,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.1,
    ),
    // oklch(100% 0 0 / 0.2)
    active: CandiColor(
      0X33FFFFFF,
      lightness: 1,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.2,
    ),
    // oklch(15% 0.005 80)
    terminalBlack: CandiColor(
      0XFF0C0B09,
      lightness: 0.15,
      chroma: 0.005,
      hue: 80,
    ),
    // oklch(68% 0.11 25)
    terminalRed: CandiColor(0XFFD47C76, lightness: 0.68, chroma: 0.11, hue: 25),
    // oklch(68% 0.09 145)
    terminalGreen: CandiColor(
      0XFF75A776,
      lightness: 0.68,
      chroma: 0.09,
      hue: 145,
    ),
    // oklch(78% 0.11 75)
    terminalYellow: CandiColor(
      0XFFE1AD63,
      lightness: 0.78,
      chroma: 0.11,
      hue: 75,
    ),
    // oklch(65% 0.13 245)
    terminalBlue: CandiColor(
      0XFF3F96D9,
      lightness: 0.65,
      chroma: 0.13,
      hue: 245,
    ),
    // oklch(72% 0.12 330)
    terminalMagenta: CandiColor(
      0XFFCF88C8,
      lightness: 0.72,
      chroma: 0.12,
      hue: 330,
    ),
    // oklch(72% 0.09 200)
    terminalCyan: CandiColor(
      0XFF56B6BB,
      lightness: 0.72,
      chroma: 0.09,
      hue: 200,
    ),
    // oklch(92% 0.005 80)
    terminalWhite: CandiColor(
      0XFFE6E4E1,
      lightness: 0.92,
      chroma: 0.005,
      hue: 80,
    ),
    // oklch(70% 0.12 25)
    red: CandiColor(0XFFDF7F78, lightness: 0.7, chroma: 0.12, hue: 25),
    // oklch(40% 0.10 25)
    redSubtle: CandiColor(0XFF742E2B, lightness: 0.4, chroma: 0.1, hue: 25),
    // oklch(78% 0.11 25)
    redSoft: CandiColor(0XFFF69B94, lightness: 0.78, chroma: 0.11, hue: 25),
    // oklch(60% 0.13 25)
    redStrong: CandiColor(0XFFC25D58, lightness: 0.6, chroma: 0.13, hue: 25),
    // oklch(55% 0.11 25)
    redOutline: CandiColor(0XFFA85550, lightness: 0.55, chroma: 0.11, hue: 25),
    // oklch(0% 0 0)
    onRed: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(70% 0.10 250)
    blue: CandiColor(0XFF6DA3DA, lightness: 0.7, chroma: 0.1, hue: 250),
    // oklch(38% 0.08 250)
    blueSubtle: CandiColor(0XFF1D456B, lightness: 0.38, chroma: 0.08, hue: 250),
    // oklch(78% 0.09 250)
    blueSoft: CandiColor(0XFF8BBCEF, lightness: 0.78, chroma: 0.09, hue: 250),
    // oklch(60% 0.11 250)
    blueStrong: CandiColor(0XFF4984BF, lightness: 0.6, chroma: 0.11, hue: 250),
    // oklch(55% 0.09 250)
    blueOutline: CandiColor(
      0XFF4675A4,
      lightness: 0.55,
      chroma: 0.09,
      hue: 250,
    ),
    // oklch(0% 0 0)
    onBlue: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(70% 0.10 145)
    green: CandiColor(0XFF76AF77, lightness: 0.7, chroma: 0.1, hue: 145),
    // oklch(40% 0.08 145)
    greenSubtle: CandiColor(0XFF29532B, lightness: 0.4, chroma: 0.08, hue: 145),
    // oklch(78% 0.09 145)
    greenSoft: CandiColor(0XFF93C794, lightness: 0.78, chroma: 0.09, hue: 145),
    // oklch(60% 0.11 145)
    greenStrong: CandiColor(0XFF539156, lightness: 0.6, chroma: 0.11, hue: 145),
    // oklch(55% 0.09 145)
    greenOutline: CandiColor(
      0XFF4E7F50,
      lightness: 0.55,
      chroma: 0.09,
      hue: 145,
    ),
    // oklch(0% 0 0)
    onGreen: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(85% 0.12 90)
    yellow: CandiColor(0XFFECCA6C, lightness: 0.85, chroma: 0.12, hue: 90),
    // oklch(50% 0.10 90)
    yellowSubtle: CandiColor(0XFF796006, lightness: 0.5, chroma: 0.1, hue: 90),
    // oklch(90% 0.11 90)
    yellowSoft: CandiColor(0XFFFADB86, lightness: 0.9, chroma: 0.11, hue: 90),
    // oklch(75% 0.13 90)
    yellowStrong: CandiColor(
      0XFFCEAA3E,
      lightness: 0.75,
      chroma: 0.13,
      hue: 90,
    ),
    // oklch(70% 0.11 90)
    yellowOutline: CandiColor(
      0XFFB99B46,
      lightness: 0.7,
      chroma: 0.11,
      hue: 90,
    ),
    // oklch(0% 0 0)
    onYellow: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(70% 0.15 330)
    magenta: CandiColor(0XFFD179CA, lightness: 0.7, chroma: 0.15, hue: 330),
    // oklch(40% 0.12 330)
    magentaSubtle: CandiColor(
      0XFF6A2A66,
      lightness: 0.4,
      chroma: 0.12,
      hue: 330,
    ),
    // oklch(78% 0.14 330)
    magentaSoft: CandiColor(
      0XFFE995E2,
      lightness: 0.78,
      chroma: 0.14,
      hue: 330,
    ),
    // oklch(60% 0.17 330)
    magentaStrong: CandiColor(
      0XFFB654B0,
      lightness: 0.6,
      chroma: 0.17,
      hue: 330,
    ),
    // oklch(55% 0.14 330)
    magentaOutline: CandiColor(
      0XFF9E4F98,
      lightness: 0.55,
      chroma: 0.14,
      hue: 330,
    ),
    // oklch(0% 0 0)
    onMagenta: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(75% 0.08 200)
    cyan: CandiColor(0XFF6CBEC2, lightness: 0.75, chroma: 0.08, hue: 200),
    // oklch(45% 0.06 200)
    cyanSubtle: CandiColor(0XFF255F62, lightness: 0.45, chroma: 0.06, hue: 200),
    // oklch(82% 0.07 200)
    cyanSoft: CandiColor(0XFF8DD2D6, lightness: 0.82, chroma: 0.07, hue: 200),
    // oklch(65% 0.09 200)
    cyanStrong: CandiColor(0XFF3EA0A5, lightness: 0.65, chroma: 0.09, hue: 200),
    // oklch(60% 0.07 200)
    cyanOutline: CandiColor(0XFF488D91, lightness: 0.6, chroma: 0.07, hue: 200),
    // oklch(0% 0 0)
    onCyan: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(70% 0.08 175)
    teal: CandiColor(0XFF65AF9C, lightness: 0.7, chroma: 0.08, hue: 175),
    // oklch(40% 0.06 175)
    tealSubtle: CandiColor(0XFF1D5246, lightness: 0.4, chroma: 0.06, hue: 175),
    // oklch(78% 0.07 175)
    tealSoft: CandiColor(0XFF87C7B5, lightness: 0.78, chroma: 0.07, hue: 175),
    // oklch(60% 0.09 175)
    tealStrong: CandiColor(0XFF3A927D, lightness: 0.6, chroma: 0.09, hue: 175),
    // oklch(55% 0.07 175)
    tealOutline: CandiColor(
      0XFF407F6F,
      lightness: 0.55,
      chroma: 0.07,
      hue: 175,
    ),
    // oklch(0% 0 0)
    onTeal: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(80% 0.10 0)
    pink: CandiColor(0XFFF3A3BB, lightness: 0.8, chroma: 0.1, hue: 0),
    // oklch(48% 0.08 0)
    pinkSubtle: CandiColor(0XFF824A5C, lightness: 0.48, chroma: 0.08, hue: 0),
    // oklch(85% 0.09 0)
    pinkSoft: CandiColor(0XFFFFB5CB, lightness: 0.85, chroma: 0.09, hue: 0),
    // oklch(70% 0.11 0)
    pinkStrong: CandiColor(0XFFD6809C, lightness: 0.7, chroma: 0.11, hue: 0),
    // oklch(65% 0.09 0)
    pinkOutline: CandiColor(0XFFBD788D, lightness: 0.65, chroma: 0.09, hue: 0),
    // oklch(0% 0 0)
    onPink: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(80% 0.10 70)
    gold: CandiColor(0XFFE7B375, lightness: 0.8, chroma: 0.1, hue: 70),
    // oklch(48% 0.08 70)
    goldSubtle: CandiColor(0XFF7A5526, lightness: 0.48, chroma: 0.08, hue: 70),
    // oklch(85% 0.09 70)
    goldSoft: CandiColor(0XFFF4C48D, lightness: 0.85, chroma: 0.09, hue: 70),
    // oklch(70% 0.11 70)
    goldStrong: CandiColor(0XFFCA924C, lightness: 0.7, chroma: 0.11, hue: 70),
    // oklch(65% 0.09 70)
    goldOutline: CandiColor(0XFFB2854F, lightness: 0.65, chroma: 0.09, hue: 70),
    // oklch(0% 0 0)
    onGold: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(60% 0.01 250)
    silver: CandiColor(0XFF7C8186, lightness: 0.6, chroma: 0.01, hue: 250),
    // oklch(35% 0.008 250)
    silverSubtle: CandiColor(
      0XFF373B3F,
      lightness: 0.35,
      chroma: 0.008,
      hue: 250,
    ),
    // oklch(68% 0.009 250)
    silverSoft: CandiColor(
      0XFF94999E,
      lightness: 0.68,
      chroma: 0.009,
      hue: 250,
    ),
    // oklch(50% 0.012 250)
    silverStrong: CandiColor(
      0XFF5E646A,
      lightness: 0.5,
      chroma: 0.012,
      hue: 250,
    ),
    // oklch(45% 0.009 250)
    silverOutline: CandiColor(
      0XFF52565A,
      lightness: 0.45,
      chroma: 0.009,
      hue: 250,
    ),
    // oklch(100% 0 0)
    onSilver: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
  );
}
