// ============================================================================
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated by scripts/build-flutter.js
// Edit the source at src/data/colors.js and run: npm run build:flutter
// ============================================================================

/// Candi Color Palette for Flutter
///
/// A Scandinavian-inspired color palette based on Nordic design principles:
/// Hygge (warmth) and Lagom (balance).
///
/// ## Quick Start
///
/// ```dart
/// import 'package:candi_colors/candi.dart';
///
/// // Access colors directly
/// Container(color: CandiColors.light.surface);
///
/// // Use convenience aliases
/// Text('Hello', style: TextStyle(color: CandiColors.dark.muted));
///
/// // Create a ThemeData
/// MaterialApp(theme: CandiColors.light.toThemeData());
/// ```
///
/// Generated from OKLCH source of truth.
/// Total colors: 63 per palette
library;

import 'package:flutter/material.dart';

/// A [Color] implementation that retains OKLCH metadata.
///
/// OKLCH is a perceptually uniform color space that provides better
/// color manipulation and contrast calculations than traditional RGB.
///
/// ## Properties
///
/// - [lightness]: Perceived lightness (0.0 = black, 1.0 = white)
/// - [chroma]: Color intensity (0.0 = gray, higher = more saturated)
/// - [hue]: Color angle in degrees (0-360)
/// - [candiOpacity]: Alpha channel (0.0 = transparent, 1.0 = opaque)
///
/// ## Example
///
/// ```dart
/// final accent = CandiColors.light.accent;
/// print(accent.lightness); // 0.52
/// print(accent.chroma);    // 0.06
/// print(accent.hue);       // 230.0
/// ```
class CandiColor extends Color {
  /// Perceived lightness in OKLCH (0.0-1.0).
  final double lightness;

  /// Color intensity/saturation in OKLCH.
  final double chroma;

  /// Hue angle in degrees (0-360).
  final double hue;

  /// Opacity/alpha value (0.0-1.0).
  final double candiOpacity;

  /// Creates a [CandiColor] with OKLCH metadata.
  const CandiColor(
    int value, {
    required this.lightness,
    required this.chroma,
    required this.hue,
    this.candiOpacity = 1.0,
  }) : super(value);

  @override
  String toString() =>
      'CandiColor(oklch(${(lightness * 100).toStringAsFixed(0)}% $chroma $hue))';
}

/// Semantic color palette for the Candi theme.
///
/// Provides a complete set of colors for building UIs with consistent
/// visual hierarchy and accessibility.
///
/// ## Color Categories
///
/// - **Backgrounds**: [bg], [surface], [elevated]
/// - **Text**: [text], [textSubtle], [textMuted]
/// - **Borders**: [border], [borderStrong], [divider]
/// - **Accent**: [accent], [accentSubtle], [onAccent]
/// - **Secondary**: [secondary], [secondarySubtle], [onSecondary]
/// - **Status**: [success], [warning], [error], [info] (with `on*` variants)
/// - **Interactive**: [link], [disabled], [focusRing], [hover], [active]
/// - **Overlays**: [overlay], [scrim], [shadowColor]
/// - **Inverse**: [inverseSurface], [inverseText]
///
/// ## Convenience Aliases
///
/// Common naming patterns from other design systems:
/// - [muted] → [textMuted]
/// - [subtle] → [textSubtle]
/// - [primary] → [accent]
/// - [onPrimary] → [onAccent]
class CandiPalette {
  const CandiPalette._({
    required this.bg,
    required this.surface,
    required this.elevated,
    required this.text,
    required this.textSubtle,
    required this.textMuted,
    required this.border,
    required this.borderStrong,
    required this.divider,
    required this.accent,
    required this.accentSubtle,
    required this.accentSoft,
    required this.accentStrong,
    required this.accentOutline,
    required this.onAccent,
    required this.secondary,
    required this.secondarySubtle,
    required this.secondarySoft,
    required this.secondaryStrong,
    required this.secondaryOutline,
    required this.onSecondary,
    required this.success,
    required this.successSubtle,
    required this.successSoft,
    required this.successStrong,
    required this.successOutline,
    required this.onSuccess,
    required this.warning,
    required this.warningSubtle,
    required this.warningSoft,
    required this.warningStrong,
    required this.warningOutline,
    required this.onWarning,
    required this.error,
    required this.errorSubtle,
    required this.errorSoft,
    required this.errorStrong,
    required this.errorOutline,
    required this.onError,
    required this.info,
    required this.infoSubtle,
    required this.infoSoft,
    required this.infoStrong,
    required this.infoOutline,
    required this.onInfo,
    required this.link,
    required this.disabled,
    required this.focusRing,
    required this.overlay,
    required this.scrim,
    required this.shadowColor,
    required this.inverseSurface,
    required this.inverseText,
    required this.hover,
    required this.active,
    required this.terminalBlack,
    required this.terminalRed,
    required this.terminalGreen,
    required this.terminalYellow,
    required this.terminalBlue,
    required this.terminalMagenta,
    required this.terminalCyan,
    required this.terminalWhite,
  });

  /// Page background color.
  final CandiColor bg;

  /// Card and section background color.
  final CandiColor surface;

  /// Elevated surface (modals, popups) background color.
  final CandiColor elevated;

  /// Primary text color.
  final CandiColor text;

  /// Secondary/subdued text color.
  final CandiColor textSubtle;

  /// Tertiary/muted text color for less important content.
  final CandiColor textMuted;

  /// Default border color.
  final CandiColor border;

  /// Emphasized border color.
  final CandiColor borderStrong;

  /// Divider/separator line color.
  final CandiColor divider;

  /// Primary accent color for buttons and interactive elements.
  final CandiColor accent;

  /// Subtle accent for hover states and backgrounds.
  final CandiColor accentSubtle;

  /// The accentSoft color.
  final CandiColor accentSoft;

  /// The accentStrong color.
  final CandiColor accentStrong;

  /// The accentOutline color.
  final CandiColor accentOutline;

  /// Text color on accent backgrounds.
  final CandiColor onAccent;

  /// Secondary action color (terracotta).
  final CandiColor secondary;

  /// Subtle secondary for backgrounds.
  final CandiColor secondarySubtle;

  /// The secondarySoft color.
  final CandiColor secondarySoft;

  /// The secondaryStrong color.
  final CandiColor secondaryStrong;

  /// The secondaryOutline color.
  final CandiColor secondaryOutline;

  /// Text color on secondary backgrounds.
  final CandiColor onSecondary;

  /// Success state color (green).
  final CandiColor success;

  /// The successSubtle color.
  final CandiColor successSubtle;

  /// The successSoft color.
  final CandiColor successSoft;

  /// The successStrong color.
  final CandiColor successStrong;

  /// The successOutline color.
  final CandiColor successOutline;

  /// Text color on success backgrounds.
  final CandiColor onSuccess;

  /// Warning state color (amber).
  final CandiColor warning;

  /// The warningSubtle color.
  final CandiColor warningSubtle;

  /// The warningSoft color.
  final CandiColor warningSoft;

  /// The warningStrong color.
  final CandiColor warningStrong;

  /// The warningOutline color.
  final CandiColor warningOutline;

  /// Text color on warning backgrounds.
  final CandiColor onWarning;

  /// Error state color (coral red).
  final CandiColor error;

  /// The errorSubtle color.
  final CandiColor errorSubtle;

  /// The errorSoft color.
  final CandiColor errorSoft;

  /// The errorStrong color.
  final CandiColor errorStrong;

  /// The errorOutline color.
  final CandiColor errorOutline;

  /// Text color on error backgrounds.
  final CandiColor onError;

  /// Informational state color (blue).
  final CandiColor info;

  /// The infoSubtle color.
  final CandiColor infoSubtle;

  /// The infoSoft color.
  final CandiColor infoSoft;

  /// The infoStrong color.
  final CandiColor infoStrong;

  /// The infoOutline color.
  final CandiColor infoOutline;

  /// Text color on info backgrounds.
  final CandiColor onInfo;

  /// Hyperlink color.
  final CandiColor link;

  /// Disabled element color.
  final CandiColor disabled;

  /// Focus ring/outline color with opacity.
  final CandiColor focusRing;

  /// Overlay color for modals (semi-transparent).
  final CandiColor overlay;

  /// Scrim color for dimming backgrounds.
  final CandiColor scrim;

  /// Shadow color with transparency.
  final CandiColor shadowColor;

  /// Inverse surface for contrast elements.
  final CandiColor inverseSurface;

  /// Text color on inverse surfaces.
  final CandiColor inverseText;

  /// Hover state overlay color.
  final CandiColor hover;

  /// Active/pressed state overlay color.
  final CandiColor active;

  /// Terminal ANSI black color.
  final CandiColor terminalBlack;

  /// Terminal ANSI red color.
  final CandiColor terminalRed;

  /// Terminal ANSI green color.
  final CandiColor terminalGreen;

  /// Terminal ANSI yellow color.
  final CandiColor terminalYellow;

  /// Terminal ANSI blue color.
  final CandiColor terminalBlue;

  /// Terminal ANSI magenta color.
  final CandiColor terminalMagenta;

  /// Terminal ANSI cyan color.
  final CandiColor terminalCyan;

  /// Terminal ANSI white color.
  final CandiColor terminalWhite;

  // ─────────────────────────────────────────────────────────────────────────
  // Convenience Aliases
  // ─────────────────────────────────────────────────────────────────────────

  /// Alias for [textMuted]. Common in design systems.
  CandiColor get muted => textMuted;

  /// Alias for [textSubtle]. Common in design systems.
  CandiColor get subtle => textSubtle;

  /// Alias for [accent]. Maps to Material's primary concept.
  CandiColor get primary => accent;

  /// Alias for [accentSubtle]. Subtle primary variant.
  CandiColor get primarySubtle => accentSubtle;

  /// Alias for [onAccent]. Text on primary backgrounds.
  CandiColor get onPrimary => onAccent;

  /// Alias for [bg]. Alternative naming convention.
  CandiColor get background => bg;

  // ─────────────────────────────────────────────────────────────────────────
  // Flutter Integration
  // ─────────────────────────────────────────────────────────────────────────

  /// Creates a [ColorScheme] from this palette.
  ///
  /// Maps Candi semantic colors to Material 3 color roles.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final scheme = CandiColors.light.toColorScheme();
  /// ThemeData(colorScheme: scheme);
  /// ```
  ColorScheme toColorScheme({Brightness? brightness}) {
    final isDark = bg.lightness < 0.5;
    return ColorScheme(
      brightness: brightness ?? (isDark ? Brightness.dark : Brightness.light),
      primary: accent,
      onPrimary: onAccent,
      primaryContainer: accentSubtle,
      onPrimaryContainer: text,
      secondary: secondary,
      onSecondary: onSecondary,
      secondaryContainer: secondarySubtle,
      onSecondaryContainer: text,
      tertiary: info,
      onTertiary: onInfo,
      tertiaryContainer: info,
      onTertiaryContainer: onInfo,
      error: error,
      onError: onError,
      errorContainer: error,
      onErrorContainer: onError,
      surface: surface,
      onSurface: text,
      onSurfaceVariant: textSubtle,
      outline: border,
      outlineVariant: borderStrong,
      shadow: shadowColor,
      scrim: scrim,
      inverseSurface: inverseSurface,
      onInverseSurface: inverseText,
      inversePrimary: accent,
      surfaceTint: accent,
    );
  }

  /// Creates a complete [ThemeData] from this palette.
  ///
  /// Provides a ready-to-use Material 3 theme with Candi colors.
  ///
  /// ## Example
  ///
  /// ```dart
  /// MaterialApp(
  ///   theme: CandiColors.light.toThemeData(),
  ///   darkTheme: CandiColors.dark.toThemeData(),
  /// );
  /// ```
  ///
  /// ## Parameters
  ///
  /// - [useMaterial3]: Use Material 3 design (default: true)
  ThemeData toThemeData({
    bool useMaterial3 = true,
  }) {
    final colorScheme = toColorScheme();
    return ThemeData(
      useMaterial3: useMaterial3,
      colorScheme: colorScheme,
      scaffoldBackgroundColor: bg,
      canvasColor: surface,
      cardColor: surface,
      dividerColor: divider,
      disabledColor: disabled,
      hoverColor: hover,
      focusColor: focusRing,
      highlightColor: active,
      splashColor: active,
      shadowColor: shadowColor,
      appBarTheme: AppBarTheme(
        backgroundColor: surface,
        foregroundColor: text,
        elevation: 0,
        surfaceTintColor: Colors.transparent,
      ),
      cardTheme: CardThemeData(
        color: surface,
        elevation: 1,
        shadowColor: shadowColor,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
        ),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: accent,
          foregroundColor: onAccent,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          foregroundColor: accent,
          side: BorderSide(color: border),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          foregroundColor: accent,
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: surface,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: BorderSide(color: border),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: BorderSide(color: border),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: BorderSide(color: accent, width: 2),
        ),
      ),
      dividerTheme: DividerThemeData(
        color: divider,
        thickness: 1,
      ),
      iconTheme: IconThemeData(
        color: textSubtle,
      ),
      textTheme: TextTheme(
        displayLarge: TextStyle(color: text),
        displayMedium: TextStyle(color: text),
        displaySmall: TextStyle(color: text),
        headlineLarge: TextStyle(color: text),
        headlineMedium: TextStyle(color: text),
        headlineSmall: TextStyle(color: text),
        titleLarge: TextStyle(color: text),
        titleMedium: TextStyle(color: text),
        titleSmall: TextStyle(color: text),
        bodyLarge: TextStyle(color: text),
        bodyMedium: TextStyle(color: text),
        bodySmall: TextStyle(color: textSubtle),
        labelLarge: TextStyle(color: text),
        labelMedium: TextStyle(color: textSubtle),
        labelSmall: TextStyle(color: textMuted),
      ),
    );
  }
}

/// Static access to light and dark Candi palettes.
///
/// ## Usage
///
/// ```dart
/// // Direct color access
/// Container(color: CandiColors.light.surface);
/// Text('Hello', style: TextStyle(color: CandiColors.dark.text));
///
/// // With theme
/// MaterialApp(
///   theme: CandiColors.light.toThemeData(),
///   darkTheme: CandiColors.dark.toThemeData(),
/// );
/// ```
abstract final class CandiColors {
  /// Light mode palette with warm, Nordic-inspired colors.
  ///
  /// Optimized for readability with WCAG AA contrast ratios.
  static const light = CandiPalette._(
    // oklch(96% 0.012 85)
    bg: CandiColor(0XFFF5F1E9, lightness: 0.96, chroma: 0.012, hue: 85),
    // oklch(93% 0.015 85)
    surface: CandiColor(0XFFECE7DD, lightness: 0.93, chroma: 0.015, hue: 85),
    // oklch(100% 0 0)
    elevated: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(25% 0.02 250)
    text: CandiColor(0XFF1A222B, lightness: 0.25, chroma: 0.02, hue: 250),
    // oklch(45% 0.015 250)
    textSubtle: CandiColor(
      0XFF4F565E,
      lightness: 0.45,
      chroma: 0.015,
      hue: 250,
    ),
    // oklch(60% 0.01 250)
    textMuted: CandiColor(0XFF7C8186, lightness: 0.6, chroma: 0.01, hue: 250),
    // oklch(88% 0.012 85)
    border: CandiColor(0XFFDBD7CF, lightness: 0.88, chroma: 0.012, hue: 85),
    // oklch(80% 0.015 85)
    borderStrong: CandiColor(
      0XFFC2BDB3,
      lightness: 0.8,
      chroma: 0.015,
      hue: 85,
    ),
    // oklch(85% 0.01 85)
    divider: CandiColor(0XFFD1CDC7, lightness: 0.85, chroma: 0.01, hue: 85),
    // oklch(52% 0.14 275)
    accent: CandiColor(0XFF535EB8, lightness: 0.52, chroma: 0.14, hue: 275),
    // oklch(85% 0.112 275)
    accentSubtle: CandiColor(
      0XFFB8C8FF,
      lightness: 0.85,
      chroma: 0.112,
      hue: 275,
    ),
    // oklch(62% 0.126 275)
    accentSoft: CandiColor(
      0XFF717ED1,
      lightness: 0.62,
      chroma: 0.126,
      hue: 275,
    ),
    // oklch(42% 0.154 275)
    accentStrong: CandiColor(
      0XFF383E9F,
      lightness: 0.42,
      chroma: 0.154,
      hue: 275,
    ),
    // oklch(37% 0.126 275)
    accentOutline: CandiColor(
      0XFF2F3581,
      lightness: 0.37,
      chroma: 0.126,
      hue: 275,
    ),
    // oklch(100% 0 0)
    onAccent: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(60% 0.10 15)
    secondary: CandiColor(0XFFB4666D, lightness: 0.6, chroma: 0.1, hue: 15),
    // oklch(93% 0.08 15)
    secondarySubtle: CandiColor(
      0XFFFFD3D7,
      lightness: 0.93,
      chroma: 0.08,
      hue: 15,
    ),
    // oklch(70% 0.09 15)
    secondarySoft: CandiColor(
      0XFFD0878C,
      lightness: 0.7,
      chroma: 0.09,
      hue: 15,
    ),
    // oklch(50% 0.11 15)
    secondaryStrong: CandiColor(
      0XFF97464F,
      lightness: 0.5,
      chroma: 0.11,
      hue: 15,
    ),
    // oklch(45% 0.09 15)
    secondaryOutline: CandiColor(
      0XFF7F3E45,
      lightness: 0.45,
      chroma: 0.09,
      hue: 15,
    ),
    // oklch(0% 0 0)
    onSecondary: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(50% 0.08 145)
    success: CandiColor(0XFF456F46, lightness: 0.5, chroma: 0.08, hue: 145),
    // oklch(83% 0.064 145)
    successSubtle: CandiColor(
      0XFFAED3AE,
      lightness: 0.83,
      chroma: 0.064,
      hue: 145,
    ),
    // oklch(60% 0.072 145)
    successSoft: CandiColor(
      0XFF658C66,
      lightness: 0.6,
      chroma: 0.072,
      hue: 145,
    ),
    // oklch(40% 0.088 145)
    successStrong: CandiColor(
      0XFF255428,
      lightness: 0.4,
      chroma: 0.088,
      hue: 145,
    ),
    // oklch(35% 0.072 145)
    successOutline: CandiColor(
      0XFF204422,
      lightness: 0.35,
      chroma: 0.072,
      hue: 145,
    ),
    // oklch(100% 0 0)
    onSuccess: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(60% 0.10 75)
    warning: CandiColor(0XFFA37734, lightness: 0.6, chroma: 0.1, hue: 75),
    // oklch(93% 0.08 75)
    warningSubtle: CandiColor(
      0XFFFFE1AC,
      lightness: 0.93,
      chroma: 0.08,
      hue: 75,
    ),
    // oklch(70% 0.09 75)
    warningSoft: CandiColor(0XFFBF965D, lightness: 0.7, chroma: 0.09, hue: 75),
    // oklch(50% 0.11 75)
    warningStrong: CandiColor(
      0XFF875800,
      lightness: 0.5,
      chroma: 0.11,
      hue: 75,
    ),
    // oklch(45% 0.09 75)
    warningOutline: CandiColor(
      0XFF724D0B,
      lightness: 0.45,
      chroma: 0.09,
      hue: 75,
    ),
    // oklch(0% 0 0)
    onWarning: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(50% 0.10 25)
    error: CandiColor(0XFF944A46, lightness: 0.5, chroma: 0.1, hue: 25),
    // oklch(83% 0.08 25)
    errorSubtle: CandiColor(0XFFF7B4AD, lightness: 0.83, chroma: 0.08, hue: 25),
    // oklch(60% 0.09 25)
    errorSoft: CandiColor(0XFFB06A65, lightness: 0.6, chroma: 0.09, hue: 25),
    // oklch(40% 0.11 25)
    errorStrong: CandiColor(0XFF782A28, lightness: 0.4, chroma: 0.11, hue: 25),
    // oklch(35% 0.09 25)
    errorOutline: CandiColor(
      0XFF612421,
      lightness: 0.35,
      chroma: 0.09,
      hue: 25,
    ),
    // oklch(100% 0 0)
    onError: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(50% 0.08 225)
    info: CandiColor(0XFF246D85, lightness: 0.5, chroma: 0.08, hue: 225),
    // oklch(83% 0.064 225)
    infoSubtle: CandiColor(
      0XFF9AD1E7,
      lightness: 0.83,
      chroma: 0.064,
      hue: 225,
    ),
    // oklch(60% 0.072 225)
    infoSoft: CandiColor(0XFF4D89A1, lightness: 0.6, chroma: 0.072, hue: 225),
    // oklch(40% 0.088 225)
    infoStrong: CandiColor(0XFF00516B, lightness: 0.4, chroma: 0.088, hue: 225),
    // oklch(35% 0.072 225)
    infoOutline: CandiColor(
      0XFF004257,
      lightness: 0.35,
      chroma: 0.072,
      hue: 225,
    ),
    // oklch(100% 0 0)
    onInfo: CandiColor(0XFFFFFFFF, lightness: 1, chroma: 0, hue: 0),
    // oklch(50% 0.08 230)
    link: CandiColor(0XFF296B88, lightness: 0.5, chroma: 0.08, hue: 230),
    // oklch(75% 0.005 250)
    disabled: CandiColor(0XFFACAEB1, lightness: 0.75, chroma: 0.005, hue: 250),
    // oklch(52% 0.06 230 / 0.4)
    focusRing: CandiColor(
      0X66437085,
      lightness: 0.52,
      chroma: 0.06,
      hue: 230,
      candiOpacity: 0.4,
    ),
    // oklch(0% 0 0 / 0.5)
    overlay: CandiColor(
      0X80000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.5,
    ),
    // oklch(0% 0 0 / 0.32)
    scrim: CandiColor(
      0X52000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.32,
    ),
    // oklch(25% 0.01 250 / 0.15)
    shadowColor: CandiColor(
      0X261E2226,
      lightness: 0.25,
      chroma: 0.01,
      hue: 250,
      candiOpacity: 0.15,
    ),
    // oklch(25% 0.015 250)
    inverseSurface: CandiColor(
      0XFF1C2229,
      lightness: 0.25,
      chroma: 0.015,
      hue: 250,
    ),
    // oklch(92% 0.01 85)
    inverseText: CandiColor(0XFFE8E4DD, lightness: 0.92, chroma: 0.01, hue: 85),
    // oklch(0% 0 0 / 0.05)
    hover: CandiColor(
      0X0D000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.05,
    ),
    // oklch(0% 0 0 / 0.1)
    active: CandiColor(
      0X1A000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.1,
    ),
    // oklch(25% 0.01 250)
    terminalBlack: CandiColor(
      0XFF1E2226,
      lightness: 0.25,
      chroma: 0.01,
      hue: 250,
    ),
    // oklch(58% 0.12 25)
    terminalRed: CandiColor(0XFFB75B55, lightness: 0.58, chroma: 0.12, hue: 25),
    // oklch(52% 0.08 145)
    terminalGreen: CandiColor(
      0XFF4A754C,
      lightness: 0.52,
      chroma: 0.08,
      hue: 145,
    ),
    // oklch(68% 0.13 70)
    terminalYellow: CandiColor(
      0XFFCB882E,
      lightness: 0.68,
      chroma: 0.13,
      hue: 70,
    ),
    // oklch(52% 0.06 230)
    terminalBlue: CandiColor(
      0XFF437085,
      lightness: 0.52,
      chroma: 0.06,
      hue: 230,
    ),
    // oklch(60% 0.15 0)
    terminalMagenta: CandiColor(
      0XFFC5547C,
      lightness: 0.6,
      chroma: 0.15,
      hue: 0,
    ),
    // oklch(65% 0.1 200)
    terminalCyan: CandiColor(
      0XFF2BA1A7,
      lightness: 0.65,
      chroma: 0.1,
      hue: 200,
    ),
    // oklch(92% 0.01 85)
    terminalWhite: CandiColor(
      0XFFE8E4DD,
      lightness: 0.92,
      chroma: 0.01,
      hue: 85,
    ),
  );

  /// Dark mode palette with cool, muted tones.
  ///
  /// Maintains visual consistency with the light theme while
  /// reducing eye strain in low-light environments.
  static const dark = CandiPalette._(
    // oklch(18% 0.015 85)
    bg: CandiColor(0XFF15110A, lightness: 0.18, chroma: 0.015, hue: 85),
    // oklch(22% 0.012 85)
    surface: CandiColor(0XFF1D1A14, lightness: 0.22, chroma: 0.012, hue: 85),
    // oklch(25% 0.015 85)
    elevated: CandiColor(0XFF252119, lightness: 0.25, chroma: 0.015, hue: 85),
    // oklch(92% 0.01 85)
    text: CandiColor(0XFFE8E4DD, lightness: 0.92, chroma: 0.01, hue: 85),
    // oklch(72% 0.008 85)
    textSubtle: CandiColor(0XFFA7A49F, lightness: 0.72, chroma: 0.008, hue: 85),
    // oklch(58% 0.006 85)
    textMuted: CandiColor(0XFF7C7A76, lightness: 0.58, chroma: 0.006, hue: 85),
    // oklch(30% 0.01 85)
    border: CandiColor(0XFF302D28, lightness: 0.3, chroma: 0.01, hue: 85),
    // oklch(40% 0.012 85)
    borderStrong: CandiColor(
      0XFF4B4740,
      lightness: 0.4,
      chroma: 0.012,
      hue: 85,
    ),
    // oklch(28% 0.008 85)
    divider: CandiColor(0XFF2B2924, lightness: 0.28, chroma: 0.008, hue: 85),
    // oklch(65% 0.13 275)
    accent: CandiColor(0XFF7987DE, lightness: 0.65, chroma: 0.13, hue: 275),
    // oklch(38% 0.104 275)
    accentSubtle: CandiColor(
      0XFF333B79,
      lightness: 0.38,
      chroma: 0.104,
      hue: 275,
    ),
    // oklch(75% 0.117 275)
    accentSoft: CandiColor(
      0XFF98A8F8,
      lightness: 0.75,
      chroma: 0.117,
      hue: 275,
    ),
    // oklch(55% 0.143 275)
    accentStrong: CandiColor(
      0XFF5B67C4,
      lightness: 0.55,
      chroma: 0.143,
      hue: 275,
    ),
    // oklch(50% 0.117 275)
    accentOutline: CandiColor(
      0XFF515CA5,
      lightness: 0.5,
      chroma: 0.117,
      hue: 275,
    ),
    // oklch(0% 0 0)
    onAccent: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(70% 0.10 15)
    secondary: CandiColor(0XFFD5848A, lightness: 0.7, chroma: 0.1, hue: 15),
    // oklch(43% 0.08 15)
    secondarySubtle: CandiColor(
      0XFF753C41,
      lightness: 0.43,
      chroma: 0.08,
      hue: 15,
    ),
    // oklch(80% 0.09 15)
    secondarySoft: CandiColor(
      0XFFF2A6AB,
      lightness: 0.8,
      chroma: 0.09,
      hue: 15,
    ),
    // oklch(60% 0.11 15)
    secondaryStrong: CandiColor(
      0XFFB8636B,
      lightness: 0.6,
      chroma: 0.11,
      hue: 15,
    ),
    // oklch(55% 0.09 15)
    secondaryOutline: CandiColor(
      0XFF9F5B60,
      lightness: 0.55,
      chroma: 0.09,
      hue: 15,
    ),
    // oklch(0% 0 0)
    onSecondary: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(75% 0.08 145)
    success: CandiColor(0XFF8EBC8F, lightness: 0.75, chroma: 0.08, hue: 145),
    // oklch(48% 0.064 145)
    successSubtle: CandiColor(
      0XFF466747,
      lightness: 0.48,
      chroma: 0.064,
      hue: 145,
    ),
    // oklch(85% 0.072 145)
    successSoft: CandiColor(
      0XFFB1DBB1,
      lightness: 0.85,
      chroma: 0.072,
      hue: 145,
    ),
    // oklch(65% 0.088 145)
    successStrong: CandiColor(
      0XFF6D9E6E,
      lightness: 0.65,
      chroma: 0.088,
      hue: 145,
    ),
    // oklch(60% 0.072 145)
    successOutline: CandiColor(
      0XFF658C66,
      lightness: 0.6,
      chroma: 0.072,
      hue: 145,
    ),
    // oklch(0% 0 0)
    onSuccess: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(80% 0.10 75)
    warning: CandiColor(0XFFE4B572, lightness: 0.8, chroma: 0.1, hue: 75),
    // oklch(53% 0.08 75)
    warningSubtle: CandiColor(
      0XFF876533,
      lightness: 0.53,
      chroma: 0.08,
      hue: 75,
    ),
    // oklch(90% 0.09 75)
    warningSoft: CandiColor(0XFFFFD69B, lightness: 0.9, chroma: 0.09, hue: 75),
    // oklch(70% 0.11 75)
    warningStrong: CandiColor(
      0XFFC69449,
      lightness: 0.7,
      chroma: 0.11,
      hue: 75,
    ),
    // oklch(65% 0.09 75)
    warningOutline: CandiColor(
      0XFFAF874D,
      lightness: 0.65,
      chroma: 0.09,
      hue: 75,
    ),
    // oklch(0% 0 0)
    onWarning: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(75% 0.10 25)
    error: CandiColor(0XFFE7958E, lightness: 0.75, chroma: 0.1, hue: 25),
    // oklch(48% 0.08 25)
    errorSubtle: CandiColor(0XFF854B46, lightness: 0.48, chroma: 0.08, hue: 25),
    // oklch(85% 0.09 25)
    errorSoft: CandiColor(0XFFFFB7B0, lightness: 0.85, chroma: 0.09, hue: 25),
    // oklch(65% 0.11 25)
    errorStrong: CandiColor(0XFFCA736D, lightness: 0.65, chroma: 0.11, hue: 25),
    // oklch(60% 0.09 25)
    errorOutline: CandiColor(0XFFB06A65, lightness: 0.6, chroma: 0.09, hue: 25),
    // oklch(0% 0 0)
    onError: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(75% 0.08 225)
    info: CandiColor(0XFF74B9D4, lightness: 0.75, chroma: 0.08, hue: 225),
    // oklch(48% 0.064 225)
    infoSubtle: CandiColor(
      0XFF316579,
      lightness: 0.48,
      chroma: 0.064,
      hue: 225,
    ),
    // oklch(85% 0.072 225)
    infoSoft: CandiColor(0XFF9AD8F1, lightness: 0.85, chroma: 0.072, hue: 225),
    // oklch(65% 0.088 225)
    infoStrong: CandiColor(
      0XFF4C9BB8,
      lightness: 0.65,
      chroma: 0.088,
      hue: 225,
    ),
    // oklch(60% 0.072 225)
    infoOutline: CandiColor(
      0XFF4D89A1,
      lightness: 0.6,
      chroma: 0.072,
      hue: 225,
    ),
    // oklch(0% 0 0)
    onInfo: CandiColor(0XFF000000, lightness: 0, chroma: 0, hue: 0),
    // oklch(65% 0.08 85)
    link: CandiColor(0XFFA68C54, lightness: 0.65, chroma: 0.08, hue: 85),
    // oklch(45% 0.005 85)
    disabled: CandiColor(0XFF565552, lightness: 0.45, chroma: 0.005, hue: 85),
    // oklch(62% 0.08 275 / 0.5)
    focusRing: CandiColor(
      0X807882B7,
      lightness: 0.62,
      chroma: 0.08,
      hue: 275,
      candiOpacity: 0.5,
    ),
    // oklch(0% 0 0 / 0.7)
    overlay: CandiColor(
      0XB3000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.7,
    ),
    // oklch(0% 0 0 / 0.6)
    scrim: CandiColor(
      0X99000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.6,
    ),
    // oklch(0% 0 0 / 0.4)
    shadowColor: CandiColor(
      0X66000000,
      lightness: 0,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.4,
    ),
    // oklch(92% 0.008 85)
    inverseSurface: CandiColor(
      0XFFE7E4DF,
      lightness: 0.92,
      chroma: 0.008,
      hue: 85,
    ),
    // oklch(25% 0.015 275)
    inverseText: CandiColor(
      0XFF1F2129,
      lightness: 0.25,
      chroma: 0.015,
      hue: 275,
    ),
    // oklch(100% 0 0 / 0.1)
    hover: CandiColor(
      0X1AFFFFFF,
      lightness: 1,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.1,
    ),
    // oklch(100% 0 0 / 0.2)
    active: CandiColor(
      0X33FFFFFF,
      lightness: 1,
      chroma: 0,
      hue: 0,
      candiOpacity: 0.2,
    ),
    // oklch(15% 0.01 275)
    terminalBlack: CandiColor(
      0XFF0A0B0F,
      lightness: 0.15,
      chroma: 0.01,
      hue: 275,
    ),
    // oklch(65% 0.05 25)
    terminalRed: CandiColor(0XFFAC8480, lightness: 0.65, chroma: 0.05, hue: 25),
    // oklch(65% 0.04 145)
    terminalGreen: CandiColor(
      0XFF819680,
      lightness: 0.65,
      chroma: 0.04,
      hue: 145,
    ),
    // oklch(75% 0.06 75)
    terminalYellow: CandiColor(
      0XFFC5A984,
      lightness: 0.75,
      chroma: 0.06,
      hue: 75,
    ),
    // oklch(65% 0.13 275)
    terminalBlue: CandiColor(
      0XFF7987DE,
      lightness: 0.65,
      chroma: 0.13,
      hue: 275,
    ),
    // oklch(70% 0.10 15)
    terminalMagenta: CandiColor(
      0XFFD5848A,
      lightness: 0.7,
      chroma: 0.1,
      hue: 15,
    ),
    // oklch(70% 0.04 225)
    terminalCyan: CandiColor(
      0XFF84A4B1,
      lightness: 0.7,
      chroma: 0.04,
      hue: 225,
    ),
    // oklch(92% 0.01 85)
    terminalWhite: CandiColor(
      0XFFE8E4DD,
      lightness: 0.92,
      chroma: 0.01,
      hue: 85,
    ),
  );
}
