const fs = require('fs');
const path = require('path');
const palette = require('../src/data/colors');
const logger = require('./logger');

const vscodeDir = path.join(__dirname, '..', 'vscode');
const themesDir = path.join(vscodeDir, 'themes');

const { toHex6: toHex, parseOklch } = require('./color-conv');

const toKebab = (str) => str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

function getColors(mode) {
    const colors = {};
    for (const [key, data] of Object.entries(palette[mode])) {
        const value = data.oklch || data.value;
        if (!value) {
            logger.warn(`[WARN] ${mode}.${key}: No oklch or value defined, skipping`);
            continue;
        }
        const parsed = parseOklch(value);
        if (parsed) {
            colors[toKebab(key)] = toHex(parsed);
        } else {
            logger.warn(`[WARN] ${mode}.${key}: Could not parse '${value}'`);
        }
    }
    return colors;
}


const lightColors = getColors('light');
const darkColors = getColors('dark');

function generateTheme(name, type, palette) {
    return {
        "$schema": "vscode://schemas/color-theme",
        "_warning": "DO NOT EDIT THIS FILE DIRECTLY. This file is auto-generated by scripts/build-vscode.js. Edit the source at src/data/colors.js and run: npm run build:vscode",
        "name": `Candi ${name}`,
        "type": type,
        "colors": {
            // General
            "focusBorder": palette['accent'],
            "foreground": palette['text'],
            "widget.shadow": palette['shadow-color'],
            "selection.background": palette['accent'] + "40",
            "descriptionForeground": palette['text-subtle'],
            "errorForeground": palette['error'],
            "icon.foreground": palette['text-subtle'],
            "sash.hoverBorder": palette['accent'],

            // Window
            "window.activeBorder": palette['border'],
            "window.inactiveBorder": palette['divider'],

            // Terminal
            "terminal.background": palette['bg'],
            "terminal.foreground": palette['text'],
            "terminal.ansiBlack": palette['terminal-black'],
            "terminal.ansiRed": palette['terminal-red'],
            "terminal.ansiGreen": palette['terminal-green'],
            "terminal.ansiYellow": palette['terminal-yellow'],
            "terminal.ansiBlue": palette['terminal-blue'],
            "terminal.ansiMagenta": palette['terminal-magenta'],
            "terminal.ansiCyan": palette['terminal-cyan'],
            "terminal.ansiWhite": palette['terminal-white'],
            "terminalCursor.background": palette['bg'],
            "terminalCursor.foreground": palette['accent'],

            // Buttons
            "button.background": palette['accent'],
            "button.foreground": palette['on-accent'],
            "button.hoverBackground": palette['accent-strong'] || palette['accent'],
            "button.secondaryBackground": palette['surface'],
            "button.secondaryForeground": palette['text'],
            "button.secondaryHoverBackground": palette['surface'],

            // Editor
            "editor.background": type === 'light' ? palette['surface'] : palette['bg'],
            "editor.foreground": palette['text'],
            "editorLineNumber.foreground": palette['text-muted'],
            "editorLineNumber.activeForeground": palette['text'],
            "editorCursor.foreground": palette['accent'],
            "editor.selectionBackground": palette['accent'] + "30",
            "editor.inactiveSelectionBackground": palette['accent'] + "15",
            "editor.lineHighlightBackground": palette['surface'],
            "editor.lineHighlightBorder": palette['divider'] + "00",
            "editorIndentGuide.background1": palette['border'],
            "editorIndentGuide.activeBackground1": palette['border-strong'],
            "editorWhitespace.foreground": palette['border'],
            "editorRuler.foreground": palette['divider'],
            "editorCodeLens.foreground": palette['text-muted'],

            // Sidebar
            "sideBar.background": palette['surface'],
            "sideBar.foreground": palette['text-subtle'],
            "sideBar.border": palette['border'],
            "sideBarTitle.foreground": palette['text'],
            "sideBarSectionHeader.background": palette['surface'],
            "sideBarSectionHeader.foreground": palette['text'],
            "sideBarSectionHeader.border": palette['border'],

            // Activity Bar
            "activityBar.background": palette['bg'],
            "activityBar.foreground": palette['text'],
            "activityBar.inactiveForeground": palette['text-muted'],
            "activityBar.border": palette['border'],
            "activityBar.activeBorder": palette['accent'],
            "activityBarBadge.background": palette['accent'],
            "activityBarBadge.foreground": palette['on-accent'],

            // Tabs
            "editorGroupHeader.tabsBackground": palette['surface'],
            "tab.activeBackground": palette['bg'],
            "tab.activeForeground": palette['text'],
            "tab.inactiveBackground": palette['surface'],
            "tab.inactiveForeground": palette['text-muted'],
            "tab.border": palette['border'],
            "tab.activeBorderTop": palette['accent'],
            "tab.unfocusedActiveBorderTop": palette['divider'],

            // Status Bar
            "statusBar.background": palette['bg'],
            "statusBar.foreground": palette['text-subtle'],
            "statusBar.border": palette['border'],
            "statusBar.debuggingBackground": palette['warning'],
            "statusBar.debuggingForeground": palette['on-warning'],
            "statusBar.noFolderBackground": palette['surface'],

            // Title Bar
            "titleBar.activeBackground": palette['bg'],
            "titleBar.activeForeground": palette['text'],
            "titleBar.inactiveBackground": palette['bg'],
            "titleBar.inactiveForeground": palette['text-muted'],
            "titleBar.border": palette['border'],

            // Lists
            "list.activeSelectionBackground": palette['accent'] + "25",
            "list.activeSelectionForeground": palette['text'],
            "list.activeSelectionIconForeground": palette['accent'],
            "list.inactiveSelectionBackground": palette['surface'],
            "list.inactiveSelectionForeground": palette['text-subtle'],
            "list.hoverBackground": palette['surface'],
            "list.hoverForeground": palette['text'],
            "list.focusBackground": palette['accent'] + "20",
            "list.focusForeground": palette['text'],
            "list.focusOutline": palette['accent'],

            // Input Controls
            "input.background": palette['surface'],
            "input.border": palette['border'],
            "input.foreground": palette['text'],
            "input.placeholderForeground": palette['text-muted'],
            "inputOption.activeBorder": palette['accent'],
            "inputValidation.errorBorder": palette['error'],
            "inputValidation.warningBorder": palette['warning'],
            "inputValidation.infoBorder": palette['info'],

            // Dropdown
            "dropdown.background": palette['surface'],
            "dropdown.border": palette['border'],
            "dropdown.foreground": palette['text'],

            // Badge
            "badge.background": palette['accent'],
            "badge.foreground": palette['on-accent'],

            // Panels
            "panel.background": palette['bg'],
            "panel.border": palette['border'],
            "panelTitle.activeBorder": palette['accent'],
            "panelTitle.activeForeground": palette['text'],
            "panelTitle.inactiveForeground": palette['text-muted'],

            // Peek View
            "peekView.border": palette['accent'],
            "peekViewEditor.background": palette['surface'],
            "peekViewEditor.matchHighlightBackground": palette['warning'] + "40",
            "peekViewResult.background": palette['surface'],
            "peekViewResult.matchHighlightBackground": palette['warning'] + "40",
            "peekViewResult.selectionBackground": palette['accent'] + "25",
            "peekViewTitle.background": palette['surface'],
            "peekViewTitleDescription.foreground": palette['text-subtle'],
            "peekViewTitleLabel.foreground": palette['text'],

            // Git Decorations
            "gitDecoration.modifiedResourceForeground": palette['warning'],
            "gitDecoration.deletedResourceForeground": palette['error'],
            "gitDecoration.untrackedResourceForeground": palette['success'],
            "gitDecoration.ignoredResourceForeground": palette['text-muted'],
            "gitDecoration.conflictingResourceForeground": palette['error'],
            "gitDecoration.submoduleResourceForeground": palette['secondary'],

            // Breadcrumbs
            "breadcrumb.foreground": palette['text-subtle'],
            "breadcrumb.background": palette['bg'],
            "breadcrumb.focusForeground": palette['text'],
            "breadcrumb.activeSelectionForeground": palette['accent'],

            // Menu
            "menu.background": palette['surface'],
            "menu.foreground": palette['text'],
            "menu.selectionBackground": palette['accent'] + "25",
            "menu.selectionForeground": palette['text'],
            "menu.separatorBackground": palette['border'],

            // Notifications
            "notificationCenter.border": palette['border'],
            "notificationCenterHeader.background": palette['surface'],
            "notificationCenterHeader.foreground": palette['text'],
            "notificationToast.border": palette['border'],
            "notifications.background": palette['surface'],
            "notifications.foreground": palette['text'],
            "notifications.border": palette['border'],
            "notificationLink.foreground": palette['accent'],

            // Debug
            "debugIcon.breakpointForeground": palette['error'],
            "debugIcon.breakpointDisabledForeground": palette['disabled'],
            "debugIcon.startForeground": palette['success'],
            "debugIcon.pauseForeground": palette['warning'],
            "debugIcon.stopForeground": palette['error'],
            "debugConsole.infoForeground": palette['info'],
            "debugConsole.errorForeground": palette['error'],
            "debugConsole.sourceForeground": palette['text-subtle'],
            "debugConsoleInputIcon.foreground": palette['accent'],

            // Testing
            "testing.iconPassed": palette['success'],
            "testing.iconFailed": palette['error'],
            "testing.iconErrored": palette['error'],
            "testing.iconQueued": palette['warning'],
            "testing.iconUnset": palette['text-muted'],
            "testing.iconSkipped": palette['disabled'],
            "testing.runAction": palette['success'],

            // Settings
            "settings.headerForeground": palette['text'],
            "settings.modifiedItemIndicator": palette['accent'],
            "settings.dropdownBackground": palette['surface'],
            "settings.dropdownBorder": palette['border'],
            "settings.checkboxBackground": palette['surface'],
            "settings.checkboxBorder": palette['border'],
            "settings.textInputBackground": palette['surface'],
            "settings.textInputHeight": palette['border'],
            "settings.numberInputBackground": palette['surface'],
            "settings.numberInputHeight": palette['border'],

            // Banner
            "banner.background": palette['accent'],
            "banner.foreground": palette['on-accent'],
            "banner.iconForeground": palette['on-accent'],

            // Scrollbar
            "scrollbar.shadow": palette['border'] + "40",
            "scrollbarSlider.background": palette['border'] + "60",
            "scrollbarSlider.hoverBackground": palette['border-strong'] + "80",
            "scrollbarSlider.activeBackground": palette['border-strong'],

            // Progress Bar
            "progressBar.background": palette['accent'],

            // Editor Widget
            "editorWidget.background": palette['surface'],
            "editorWidget.border": palette['border'],
            "editorWidget.foreground": palette['text'],
            "editorSuggestWidget.background": palette['surface'],
            "editorSuggestWidget.border": palette['border'],
            "editorSuggestWidget.foreground": palette['text'],
            "editorSuggestWidget.highlightForeground": palette['accent'],
            "editorSuggestWidget.selectedBackground": palette['accent'] + "25",

            // Editor Hover
            "editorHoverWidget.background": palette['surface'],
            "editorHoverWidget.border": palette['border'],
            "editorHoverWidget.foreground": palette['text'],

            // Symbol Icons
            "symbolIcon.arrayForeground": palette['text'],
            "symbolIcon.booleanForeground": palette['syntax-const'],
            "symbolIcon.classForeground": palette['syntax-type'],
            "symbolIcon.constantForeground": palette['syntax-const'],
            "symbolIcon.constructorForeground": palette['syntax-type'],
            "symbolIcon.enumeratorForeground": palette['syntax-type'],
            "symbolIcon.enumeratorMemberForeground": palette['syntax-const'],
            "symbolIcon.eventForeground": palette['warning'],
            "symbolIcon.fieldForeground": palette['secondary'],
            "symbolIcon.fileForeground": palette['text-subtle'],
            "symbolIcon.folderForeground": palette['text-subtle'],
            "symbolIcon.functionForeground": palette['syntax-func'],
            "symbolIcon.interfaceForeground": palette['syntax-type'],
            "symbolIcon.keyForeground": palette['text'],
            "symbolIcon.keywordForeground": palette['syntax-keyword'],
            "symbolIcon.methodForeground": palette['syntax-func'],
            "symbolIcon.moduleForeground": palette['secondary'],
            "symbolIcon.namespaceForeground": palette['secondary'],
            "symbolIcon.nullForeground": palette['syntax-const'],
            "symbolIcon.numberForeground": palette['syntax-const'],
            "symbolIcon.objectForeground": palette['text'],
            "symbolIcon.operatorForeground": palette['text'],
            "symbolIcon.packageForeground": palette['secondary'],
            "symbolIcon.propertyForeground": palette['secondary'],
            "symbolIcon.referenceForeground": palette['text'],
            "symbolIcon.snippetForeground": palette['text-muted'],
            "symbolIcon.stringForeground": palette['syntax-string'],
            "symbolIcon.structForeground": palette['syntax-type'],
            "symbolIcon.textForeground": palette['text'],
            "symbolIcon.typeParameterForeground": palette['syntax-type'],
            "symbolIcon.unitForeground": palette['text'],
            "symbolIcon.variableForeground": palette['syntax-var'],

            // Bracket Pair Colorization (using primitives)
            "editorBracketHighlight.foreground1": palette['blue'],
            "editorBracketHighlight.foreground2": palette['magenta'],
            "editorBracketHighlight.foreground3": palette['cyan'],
            "editorBracketHighlight.foreground4": palette['yellow'],
            "editorBracketHighlight.foreground5": palette['green'],
            "editorBracketHighlight.foreground6": palette['red'],
            "editorBracketHighlight.unexpectedBracket.foreground": palette['error'],

            // Bracket Pair Guides
            "editorBracketPairGuide.activeBackground1": palette['blue'] + "80",
            "editorBracketPairGuide.activeBackground2": palette['magenta'] + "80",
            "editorBracketPairGuide.activeBackground3": palette['cyan'] + "80",
            "editorBracketPairGuide.activeBackground4": palette['yellow'] + "80",
            "editorBracketPairGuide.activeBackground5": palette['green'] + "80",
            "editorBracketPairGuide.activeBackground6": palette['red'] + "80",

            // Diff Editor
            "diffEditor.insertedTextBackground": palette['success'] + "15",
            "diffEditor.removedTextBackground": palette['error'] + "15",
            "diffEditor.diagonalFill": palette['border'] + "40",
            "diffEditor.insertedLineBackground": palette['success'] + "10",
            "diffEditor.removedLineBackground": palette['error'] + "10",
            "diffEditorGutter.insertedLineBackground": palette['success'] + "20",
            "diffEditorGutter.removedLineBackground": palette['error'] + "20",
            "diffEditorOverview.insertedForeground": palette['success'] + "80",
            "diffEditorOverview.removedForeground": palette['error'] + "80",

            // Merge Conflicts
            "merge.currentHeaderBackground": palette['success'] + "40",
            "merge.currentContentBackground": palette['success'] + "10",
            "merge.incomingHeaderBackground": palette['accent'] + "40",
            "merge.incomingContentBackground": palette['accent'] + "10",
            "merge.commonHeaderBackground": palette['warning'] + "40",
            "merge.commonContentBackground": palette['warning'] + "10",
            "editorOverviewRuler.currentContentForeground": palette['success'],
            "editorOverviewRuler.incomingContentForeground": palette['accent'],
            "editorOverviewRuler.commonContentForeground": palette['warning'],

            // Minimap
            "minimap.findMatchHighlight": palette['warning'],
            "minimap.errorHighlight": palette['error'],
            "minimap.warningHighlight": palette['warning'],
            "minimap.selectionHighlight": palette['accent'] + "40",
            "minimap.background": palette['bg'],
            "minimapSlider.background": palette['border'] + "40",
            "minimapSlider.hoverBackground": palette['border'] + "60",
            "minimapSlider.activeBackground": palette['border-strong'] + "80",

            // Command Center
            "commandCenter.foreground": palette['text'],
            "commandCenter.activeBackground": palette['surface'],
            "commandCenter.background": palette['bg'],
            "commandCenter.border": palette['border'],

            // Keybinding Label
            "keybindingLabel.background": palette['surface'],
            "keybindingLabel.foreground": palette['text'],
            "keybindingLabel.border": palette['border'],
            "keybindingLabel.bottomBorder": palette['border-strong'],

            // Notebooks
            "notebook.cellBorderColor": palette['border'],
            "notebook.focusedCellBorder": palette['accent'],
            "notebook.cellEditorBackground": palette['bg'],
            "notebook.outputContainerBackgroundColor": palette['surface'],
            "notebook.cellToolbarSeparator": palette['border'],
            "notebookStatusErrorIcon.foreground": palette['error'],
            "notebookStatusRunningIcon.foreground": palette['success'],
            "notebookStatusSuccessIcon.foreground": palette['success'],

            // Charts
            "charts.foreground": palette['text'],
            "charts.lines": palette['border'],
            "charts.red": palette['red'],
            "charts.blue": palette['blue'],
            "charts.yellow": palette['yellow'],
            "charts.orange": palette['red-soft'] || palette['warning'],
            "charts.green": palette['green'],
            "charts.purple": palette['magenta'],

            // Inline Chat
            "inlineChat.background": palette['surface'],
            "inlineChat.border": palette['border'],
            "inlineChat.shadow": palette['shadow-color'],
            "inlineChat.regionHighlight": palette['accent'] + "20",
        },
        "semanticHighlighting": true,
        "semanticTokenColors": {
            // TypeScript/JavaScript
            "class:typescript": palette['syntax-type'],
            "interface:typescript": palette['syntax-type'],
            "enum:typescript": palette['syntax-type'],
            "enumMember:typescript": palette['syntax-const'],
            "namespace:typescript": palette['secondary'],
            "variable.defaultLibrary:typescript": palette['syntax-const'],
            "property.defaultLibrary:typescript": palette['syntax-const'],
            "class:typescriptreact": palette['syntax-type'],
            "interface:typescriptreact": palette['syntax-type'],
            "enum:typescriptreact": palette['syntax-type'],
            "enumMember:typescriptreact": palette['syntax-const'],
            "namespace:typescriptreact": palette['secondary'],
            "variable.defaultLibrary:typescriptreact": palette['syntax-const'],
            "property.defaultLibrary:typescriptreact": palette['syntax-const'],
            "variable.defaultLibrary:javascript": palette['syntax-const'],
            "property.defaultLibrary:javascript": palette['syntax-const'],
            "variable.defaultLibrary:javascriptreact": palette['syntax-const'],
            "property.defaultLibrary:javascriptreact": palette['syntax-const'],
            // Python
            "intrinsic:python": palette['syntax-const'],
            "module:python": palette['secondary'],
            "class:python": palette['syntax-type'],
            "decorator:python": palette['secondary'],
            // Rust
            "macro:rust": palette['syntax-func'],
            "namespace:rust": palette['secondary'],
            "selfKeyword:rust": palette['syntax-keyword'],
            "lifetime:rust": palette['secondary'],
            // Go
            "namespace:go": palette['secondary'],
        },
        "tokenColors": [
            {
                "scope": ["comment", "punctuation.definition.comment"],
                "settings": { "foreground": palette['text-muted'], "fontStyle": "italic" }
            },
            {
                "scope": ["string", "punctuation.definition.string", "string.quoted.double", "string.quoted.single"],
                "settings": { "foreground": palette['syntax-string'] || palette['success'] }
            },
            {
                "scope": ["keyword", "storage.type", "storage.modifier", "keyword.control", "keyword.operator.new", "keyword.operator.expression", "keyword.operator.logical", "keyword.operator.word"],
                "settings": { "foreground": palette['syntax-keyword'] || palette['accent'], "fontStyle": "bold" }
            },
            {
                "scope": ["constant.numeric", "constant.language", "constant.character", "constant.other", "variable.other.constant"],
                "settings": { "foreground": palette['syntax-const'] || palette['secondary'] }
            },
            {
                "scope": ["variable", "variable.other", "variable.language"],
                "settings": { "foreground": palette['text'] }
            },
            {
                "scope": ["variable.parameter", "meta.parameters"],
                "settings": { "foreground": palette['syntax-var'] || palette['text-subtle'] }
            },
            {
                "scope": ["entity.name.function", "support.function", "meta.function-call"],
                "settings": { "foreground": palette['syntax-func'] }
            },
            {
                "scope": ["entity.name.type", "entity.name.class", "support.type", "support.class", "entity.name.type.class", "entity.name.type.enum"],
                "settings": { "foreground": palette['syntax-type'] }
            },
            {
                "scope": ["entity.name.tag", "punctuation.definition.tag"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["entity.other.attribute-name"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["entity.name.namespace", "entity.name.module"],
                "settings": { "foreground": palette['syntax-type'] }
            },
            {
                "scope": ["punctuation.separator", "punctuation.terminator", "punctuation.accessor", "punctuation.section.embedded"],
                "settings": { "foreground": palette['text-subtle'] }
            },
            {
                "scope": ["punctuation.definition.parameters", "punctuation.definition.block", "punctuation.definition.bracket"],
                "settings": { "foreground": palette['text-muted'] }
            },
            {
                "scope": ["markup.heading", "entity.name.section"],
                "settings": { "foreground": palette['accent'], "fontStyle": "bold" }
            },
            {
                "scope": ["markup.bold"],
                "settings": { "foreground": palette['text'], "fontStyle": "bold" }
            },
            {
                "scope": ["markup.italic"],
                "settings": { "foreground": palette['text'], "fontStyle": "italic" }
            },
            {
                "scope": ["markup.inline.raw", "markup.fenced_code"],
                "settings": { "foreground": palette['syntax-string'] || palette['success'] }
            },
            {
                "scope": ["markup.quote"],
                "settings": { "foreground": palette['text-subtle'], "fontStyle": "italic" }
            },
            {
                "scope": ["markup.list"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["markup.underline.link", "string.other.link"],
                "settings": { "foreground": palette['accent'], "fontStyle": "underline" }
            },
            {
                "scope": ["constant.character.escape", "constant.other.placeholder"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["string.regexp", "constant.regexp"],
                "settings": { "foreground": palette['warning'] }
            },
            {
                "scope": ["support.constant", "meta.property-name", "meta.object-literal.key"],
                "settings": { "foreground": palette['text'] }
            },
            {
                "scope": ["entity.other.inherited-class"],
                "settings": { "foreground": palette['secondary'], "fontStyle": "italic" }
            },
            {
                "scope": ["storage", "storage.type.function"],
                "settings": { "foreground": palette['accent'], "fontStyle": "bold" }
            },
            {
                "scope": ["support.variable", "variable.other.readwrite"],
                "settings": { "foreground": palette['text'] }
            },
            {
                "scope": ["support.module", "support.node"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["punctuation.definition.template-expression"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["meta.embedded", "source.groovy.embedded"],
                "settings": { "foreground": palette['text'] }
            },
            {
                "scope": ["support.type.property-name"],
                "settings": { "foreground": palette['text'] }
            },
            {
                "scope": ["entity.name.operator"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["keyword.operator"],
                "settings": { "foreground": palette['text-subtle'] }
            },
            {
                "scope": ["invalid", "invalid.illegal"],
                "settings": { "foreground": palette['error'] }
            },
            {
                "scope": ["invalid.deprecated"],
                "settings": { "foreground": palette['warning'] }
            },
            {
                "scope": ["meta.diff", "meta.diff.header"],
                "settings": { "foreground": palette['text-muted'], "fontStyle": "italic" }
            },
            {
                "scope": ["markup.inserted"],
                "settings": { "foreground": palette['success'] }
            },
            {
                "scope": ["markup.deleted"],
                "settings": { "foreground": palette['error'] }
            },
            {
                "scope": ["markup.changed"],
                "settings": { "foreground": palette['warning'] }
            },
            {
                "scope": ["meta.selector", "entity.other.attribute-name.class.css", "entity.other.attribute-name.id.css"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["support.type.property-name.css"],
                "settings": { "foreground": palette['text'] }
            },
            {
                "scope": ["constant.other.color"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["entity.other.attribute-name.html", "entity.other.attribute-name.xml"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["punctuation.definition.entity"],
                "settings": { "foreground": palette['text-muted'] }
            },
            {
                "scope": ["support.type.vendored.property-name"],
                "settings": { "foreground": palette['text-subtle'] }
            },
            {
                "scope": ["source.css support.type.property-name", "source.sass support.type.property-name", "source.scss support.type.property-name", "source.less support.type.property-name", "source.stylus support.type.property-name"],
                "settings": { "foreground": palette['text'] }
            },
            {
                "scope": ["support.constant.mathematical-symbols"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["token.info-token"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["token.warn-token"],
                "settings": { "foreground": palette['warning'] }
            },
            {
                "scope": ["token.error-token"],
                "settings": { "foreground": palette['error'] }
            },
            {
                "scope": ["token.debug-token"],
                "settings": { "foreground": palette['text-muted'] }
            },
            {
                "scope": ["comment.block.documentation", "comment.documentation", "string.quoted.docstring"],
                "settings": { "foreground": palette['text-subtle'], "fontStyle": "italic" }
            },
            {
                "scope": ["entity.name.exception"],
                "settings": { "foreground": palette['error'], "fontStyle": "bold" }
            },
            {
                "scope": ["keyword.other.important"],
                "settings": { "foreground": palette['error'], "fontStyle": "bold" }
            },
            {
                "scope": ["markup.error"],
                "settings": { "foreground": palette['error'] }
            },
            {
                "scope": ["meta.diff.range", "meta.diff.index", "meta.separator"],
                "settings": { "foreground": palette['text-subtle'] }
            },
            {
                "scope": ["meta.diff.header.from-file"],
                "settings": { "foreground": palette['error'] }
            },
            {
                "scope": ["meta.diff.header.to-file"],
                "settings": { "foreground": palette['success'] }
            },
            // HTML/XML specific
            {
                "scope": ["entity.name.tag.html", "entity.name.tag.xml", "entity.name.tag.localname.xml"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["entity.other.attribute-name.html", "entity.other.attribute-name.xml", "entity.other.attribute-name.localname.xml"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["string.quoted.double.html", "string.quoted.single.html", "punctuation.definition.string.begin.html", "punctuation.definition.string.end.html"],
                "settings": { "foreground": palette['syntax-string'] }
            },
            {
                "scope": ["punctuation.definition.tag.begin.html", "punctuation.definition.tag.end.html", "punctuation.definition.tag.xml"],
                "settings": { "foreground": palette['text-muted'] }
            },
            // CSS specific
            {
                "scope": ["entity.other.attribute-name.class.css", "entity.other.attribute-name.id.css"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["support.type.property-name.css", "meta.property-name.css"],
                "settings": { "foreground": palette['syntax-var'] }
            },
            {
                "scope": ["support.constant.property-value.css", "meta.property-value.css", "constant.numeric.css"],
                "settings": { "foreground": palette['syntax-const'] }
            },
            {
                "scope": ["keyword.other.unit.css", "keyword.other.unit"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["entity.other.attribute-name.pseudo-class.css", "entity.other.attribute-name.pseudo-element.css"],
                "settings": { "foreground": palette['syntax-func'] }
            },
            {
                "scope": ["entity.name.tag.css"],
                "settings": { "foreground": palette['syntax-type'] }
            },
            {
                "scope": ["punctuation.definition.entity.css", "punctuation.separator.key-value.css", "punctuation.terminator.rule.css"],
                "settings": { "foreground": palette['text-muted'] }
            },
            // SASS/SCSS specific
            {
                "scope": ["keyword.control.at-rule.include.scss", "keyword.control.at-rule.mixin.scss", "keyword.control.at-rule.extend.scss", "keyword.control.at-rule.import.scss", "keyword.control.at-rule.use.scss"],
                "settings": { "foreground": palette['syntax-keyword'] }
            },
            {
                "scope": ["variable.scss", "variable.sass"],
                "settings": { "foreground": palette['syntax-var'] }
            },
            // JavaScript specific
            {
                "scope": ["storage.type.js", "storage.type.function.arrow.js"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["punctuation.accessor.js", "keyword.operator.accessor.js"],
                "settings": { "foreground": palette['text-muted'] }
            },
            {
                "scope": ["punctuation.definition.block.tag.jsdoc"],
                "settings": { "foreground": palette['secondary'] }
            },
            // JSX specific
            {
                "scope": ["entity.name.tag.js.jsx", "support.class.component.jsx", "support.class.component.js.jsx"],
                "settings": { "foreground": palette['syntax-type'] }
            },
            {
                "scope": ["entity.other.attribute-name.jsx", "entity.other.attribute-name.js.jsx"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["punctuation.definition.tag.jsx", "punctuation.definition.tag.begin.js.jsx", "punctuation.definition.tag.end.js.jsx"],
                "settings": { "foreground": palette['text-muted'] }
            },
            // TypeScript specific
            {
                "scope": ["storage.type.ts", "storage.type.function.arrow.ts", "storage.type.type.ts"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["entity.name.type.ts", "entity.name.type.interface.ts", "entity.name.type.alias.ts", "entity.name.type.class.ts", "entity.name.type.enum.ts"],
                "settings": { "foreground": palette['syntax-type'] }
            },
            {
                "scope": ["keyword.control.import.ts", "keyword.control.export.ts", "storage.type.namespace.ts"],
                "settings": { "foreground": palette['syntax-keyword'] }
            },
            {
                "scope": ["keyword.operator.type.annotation.ts", "punctuation.accessor.ts"],
                "settings": { "foreground": palette['text-muted'] }
            },
            // TSX specific
            {
                "scope": ["entity.name.tag.tsx", "support.class.component.tsx"],
                "settings": { "foreground": palette['syntax-type'] }
            },
            {
                "scope": ["entity.other.attribute-name.tsx"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["storage.type.tsx", "storage.type.function.arrow.tsx", "storage.type.type.tsx"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["entity.name.type.tsx", "entity.name.type.interface.tsx", "entity.name.type.alias.tsx"],
                "settings": { "foreground": palette['syntax-type'] }
            },
            // Python specific
            {
                "scope": ["entity.name.function.decorator.python", "punctuation.definition.decorator.python"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["support.function.builtin.python", "support.type.python"],
                "settings": { "foreground": palette['syntax-func'] }
            },
            {
                "scope": ["constant.language.python", "variable.language.special.self.python"],
                "settings": { "foreground": palette['syntax-keyword'] }
            },
            {
                "scope": ["string.quoted.docstring.multi.python", "string.quoted.docstring.raw.multi.python"],
                "settings": { "foreground": palette['text-subtle'], "fontStyle": "italic" }
            },
            {
                "scope": ["meta.function-call.generic.python"],
                "settings": { "foreground": palette['syntax-func'] }
            },
            // Go specific
            {
                "scope": ["keyword.package.go", "keyword.import.go"],
                "settings": { "foreground": palette['syntax-keyword'] }
            },
            {
                "scope": ["entity.name.package.go"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["support.function.builtin.go"],
                "settings": { "foreground": palette['syntax-func'] }
            },
            {
                "scope": ["keyword.type.go", "storage.type.go"],
                "settings": { "foreground": palette['syntax-type'] }
            },
            // Rust specific
            {
                "scope": ["entity.name.function.macro.rust", "meta.macro.rust"],
                "settings": { "foreground": palette['syntax-func'] }
            },
            {
                "scope": ["keyword.other.crate.rust", "keyword.other.mod.rust", "keyword.other.use.rust"],
                "settings": { "foreground": palette['syntax-keyword'] }
            },
            {
                "scope": ["storage.type.rust", "entity.name.type.rust"],
                "settings": { "foreground": palette['syntax-type'] }
            },
            {
                "scope": ["variable.language.self.rust"],
                "settings": { "foreground": palette['syntax-keyword'] }
            },
            {
                "scope": ["storage.modifier.lifetime.rust", "entity.name.lifetime.rust", "punctuation.definition.lifetime.rust"],
                "settings": { "foreground": palette['secondary'] }
            },
            {
                "scope": ["meta.attribute.rust"],
                "settings": { "foreground": palette['text-subtle'] }
            },
            // JSON specific
            {
                "scope": ["support.type.property-name.json"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["string.quoted.double.json"],
                "settings": { "foreground": palette['syntax-string'] }
            },
            {
                "scope": ["constant.language.json"],
                "settings": { "foreground": palette['syntax-const'] }
            },
            // YAML specific
            {
                "scope": ["entity.name.tag.yaml"],
                "settings": { "foreground": palette['accent'] }
            },
            {
                "scope": ["string.unquoted.plain.out.yaml", "string.quoted.single.yaml", "string.quoted.double.yaml"],
                "settings": { "foreground": palette['syntax-string'] }
            },
            {
                "scope": ["constant.language.boolean.yaml", "constant.language.null.yaml"],
                "settings": { "foreground": palette['syntax-const'] }
            },
            // Shell/Bash specific
            {
                "scope": ["variable.other.normal.shell", "variable.other.positional.shell", "variable.other.special.shell"],
                "settings": { "foreground": palette['syntax-var'] }
            },
            {
                "scope": ["keyword.control.shell", "keyword.operator.logical.shell"],
                "settings": { "foreground": palette['syntax-keyword'] }
            },
            {
                "scope": ["support.function.builtin.shell"],
                "settings": { "foreground": palette['syntax-func'] }
            },
            // SQL specific
            {
                "scope": ["keyword.other.DML.sql", "keyword.other.DDL.sql", "keyword.other.sql"],
                "settings": { "foreground": palette['syntax-keyword'] }
            },
            {
                "scope": ["constant.other.database-name.sql", "constant.other.table-name.sql"],
                "settings": { "foreground": palette['syntax-type'] }
            },
            // Dockerfile specific
            {
                "scope": ["keyword.other.special-method.dockerfile"],
                "settings": { "foreground": palette['syntax-keyword'], "fontStyle": "bold" }
            },
            // GraphQL specific
            {
                "scope": ["keyword.type.graphql", "support.type.graphql"],
                "settings": { "foreground": palette['syntax-type'] }
            },
            {
                "scope": ["variable.graphql", "variable.arguments.graphql"],
                "settings": { "foreground": palette['syntax-var'] }
            }
        ]
    };
}

// Ensure directories exist
if (!fs.existsSync(vscodeDir)) fs.mkdirSync(vscodeDir);
if (!fs.existsSync(themesDir)) fs.mkdirSync(themesDir);

// 2. Generate Themes
fs.writeFileSync(path.join(themesDir, 'Candi Light-color-theme.json'), JSON.stringify(generateTheme('Light', 'light', lightColors), null, 4));
fs.writeFileSync(path.join(themesDir, 'Candi Dark-color-theme.json'), JSON.stringify(generateTheme('Dark', 'dark', darkColors), null, 4));

// 3. Generate extension package.json

const version = require('../package.json').version;

const extensionPackage = {
    "name": "vscode-theme-candi",
    "displayName": "Candi Theme",
    "description": "Scandinavian design theme.",
    "repository": {
        "type": "git",
        "url": "https://github.com/wtasg/candi.git"
    },
    "version": version,
    "publisher": "wtasg",
    "engines": { "vscode": "^1.0.0" },
    "categories": ["Themes"],
    "contributes": {
        "themes": [
            {
                "label": "Candi Light",
                "uiTheme": "vs",
                "path": "./themes/Candi Light-color-theme.json"
            },
            {
                "label": "Candi Dark",
                "uiTheme": "vs-dark",
                "path": "./themes/Candi Dark-color-theme.json"
            }
        ]
    }
};

fs.writeFileSync(path.join(vscodeDir, 'package.json'), JSON.stringify(extensionPackage, null, 4));

if (logger.isVerbose) {
    logger.log('\nBuild complete!');
    logger.log('  - Generated vscode/ extension');
}
