const fs = require('fs');
const path = require('path');
const palette = require('../src/data/colors');
const logger = require('./logger');

const vimDir = path.join(__dirname, '..', 'vim');
const colorsDir = path.join(vimDir, 'colors');

const { toHex6: toHex, parseOklch } = require('./color-conv');

const toKebab = (str) => str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

function getColors(mode) {
    const colors = {};
    for (const [key, data] of Object.entries(palette[mode])) {
        const value = data.oklch || data.value;
        const parsed = parseOklch(value);
        if (parsed) colors[toKebab(key)] = toHex(parsed);
    }
    return colors;
}


const lightColors = getColors('light');
const darkColors = getColors('dark');

/**
 * Get the last modified date from existing file, or use current date if file doesn't exist
 */
function getLastModifiedDate(filePath) {
    if (fs.existsSync(filePath)) {
        const content = fs.readFileSync(filePath, 'utf8');
        const match = content.match(/Last Modified: (\d{4}-\d{2}-\d{2})/);
        if (match) {
            return match[1];
        }
        // If file exists but no date found, or if the file is being regenerated
        // This log is for when a file exists but its content doesn't have the date,
        // or if the file is being overwritten with new content.
        if (logger.isVerbose) {
            const relPath = path.relative(process.cwd(), filePath);
            logger.log(`  - ${relPath} unchanged`);
        }
    }
    return new Date().toISOString().split('T')[0];
}

/**
 * Convert hex color to nearest xterm-256 color code
 */
function hexToXterm256(hex) {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);

    const avg = (r + g + b) / 3;
    const isGray = Math.abs(r - avg) < 10 && Math.abs(g - avg) < 10 && Math.abs(b - avg) < 10;

    if (isGray) {
        if (avg < 8) return 16;
        if (avg > 248) return 231;
        return Math.min(255, Math.round(232 + (avg - 8) / 10));
    }

    const rIndex = Math.round(r / 255 * 5);
    const gIndex = Math.round(g / 255 * 5);
    const bIndex = Math.round(b / 255 * 5);

    return 16 + (36 * rIndex) + (6 * gIndex) + bIndex;
}

function generateVimTheme(name, background, palette, lastModified) {
    const isDark = background === 'dark';

    // Helper to generate highlight group
    const hi = (group, fgKey, bgKey = null, attr = 'NONE') => {
        const fg = fgKey ? palette[fgKey] : 'NONE';
        const bg = bgKey ? palette[bgKey] : 'NONE';
        const cfg = fgKey ? hexToXterm256(palette[fgKey]) : 'NONE';
        const cbg = bgKey ? hexToXterm256(palette[bgKey]) : 'NONE';

        if (attr.startsWith('s:')) {
            return `execute "hi ${group.padEnd(24)} guifg=${fg} guibg=${bg} ctermfg=${cfg} ctermbg=${cbg} gui=" . ${attr} . " cterm=" . ${attr}`;
        }
        return `hi ${group.padEnd(24)} guifg=${fg} ctermfg=${cfg} guibg=${bg} ctermbg=${cbg} gui=${attr} cterm=${attr}`;
    };

    const link = (from, to) => `hi! link ${from.padEnd(24)} ${to}`;

    return `" =============================================================================
" DO NOT EDIT THIS FILE DIRECTLY
" This file is auto-generated by scripts/build-vim.js
" Edit the source at src/data/colors.js and run: npm run build:vim
" =============================================================================
"
" File: candi-${background}.vim
" Description: Scandinavian design colorscheme for Vim
" Author: Candi Design System
" Source: https://github.com/wtasg/candi
" Last Modified: ${lastModified}
" -----------------------------------------------------------------------------

" Initialization: {{{

if version > 580
  hi clear
  if exists("syntax_on")
    syntax reset
  endif
endif

let g:colors_name = "candi-${background}"
set background=${background}

if !(has('termguicolors') && &termguicolors) && !has('gui_running') && &t_Co != 256
  finish
endif

" }}}
" Global Settings: {{{

if !exists('g:candi_bold')
  let g:candi_bold = 1
endif

if !exists('g:candi_italic')
  if has('gui_running') || $TERM_ITALICS == 'true'
    let g:candi_italic = 1
  else
    let g:candi_italic = 0
  endif
endif

if !exists('g:candi_underline')
  let g:candi_underline = 1
endif

if !exists('g:candi_undercurl')
  let g:candi_undercurl = 1
endif

if !exists('g:candi_inverse')
  let g:candi_inverse = 1
endif

if !exists('g:candi_italic_comments')
  let g:candi_italic_comments = 1
endif

if !exists('g:candi_italic_strings')
  let g:candi_italic_strings = 0
endif

" }}}
" Emphasis Setup: {{{

let s:bold = g:candi_bold == 1 ? 'bold' : 'NONE'
let s:italic = g:candi_italic == 1 ? 'italic' : 'NONE'
let s:underline = g:candi_underline == 1 ? 'underline' : 'NONE'
let s:undercurl = g:candi_undercurl == 1 ? 'undercurl' : 'NONE'
let s:inverse = g:candi_inverse == 1 ? 'inverse' : 'NONE'
let s:italic_comments = g:candi_italic_comments == 1 ? 'italic' : 'NONE'
let s:italic_strings = g:candi_italic_strings == 1 ? 'italic' : 'NONE'

" }}}
" Terminal Colors (Neovim): {{{

if has('nvim')
  let g:terminal_color_0  = '${palette['terminal-black']}'
  let g:terminal_color_1  = '${palette['terminal-red']}'
  let g:terminal_color_2  = '${palette['terminal-green']}'
  let g:terminal_color_3  = '${palette['terminal-yellow']}'
  let g:terminal_color_4  = '${palette['terminal-blue']}'
  let g:terminal_color_5  = '${palette['terminal-magenta']}'
  let g:terminal_color_6  = '${palette['terminal-cyan']}'
  let g:terminal_color_7  = '${palette['text']}'
  let g:terminal_color_8  = '${palette['text-muted']}'
  let g:terminal_color_9  = '${palette['error']}'
  let g:terminal_color_10 = '${palette['success']}'
  let g:terminal_color_11 = '${palette['warning']}'
  let g:terminal_color_12 = '${palette['accent']}'
  let g:terminal_color_13 = '${palette['syntax-keyword']}'
  let g:terminal_color_14 = '${palette['syntax-var']}'
  let g:terminal_color_15 = '${palette['text']}'
endif

" }}}
" Vanilla Colorscheme: {{{
" General UI: {{{

${hi('Normal', 'text', 'bg')}
${hi('CursorLine', null, 'surface')}
${hi('CursorColumn', null, 'surface')}
${hi('ColorColumn', null, 'surface')}
${hi('Conceal', 'accent')}

${hi('LineNr', 'text-muted', 'bg')}
${hi('CursorLineNr', 'accent', 'bg', 's:bold')}
${hi('SignColumn', null, 'bg')}
${hi('FoldColumn', 'text-muted', 'bg')}
${hi('Folded', 'text-subtle', 'surface', 's:italic')}

${hi('Visual', null, 'accent-soft')}
${link('VisualNOS', 'Visual')}

${hi('Search', 'on-warning', 'warning')}
${hi('IncSearch', 'on-accent', 'accent', 's:bold')}

${hi('MatchParen', 'accent', 'surface', 's:bold')}

${hi('StatusLine', isDark ? 'text' : 'on-accent', isDark ? 'accent-subtle' : 'accent', 's:bold')}
${hi('StatusLineNC', 'text-subtle', 'surface')}
${hi('StatusLineTerm', 'on-accent', 'accent', 's:bold')}
${hi('StatusLineTermNC', 'text-muted', 'surface')}
${hi('VertSplit', 'border', 'bg')}
${hi('WildMenu', 'on-accent', 'accent', 's:bold')}

${hi('TabLine', 'text-muted', 'surface')}
${hi('TabLineFill', 'border', 'surface')}
${hi('TabLineSel', 'on-accent', 'accent', 's:bold')}

" Statusline segments (commonly used by plugins like Airline/Lightline)
${hi('User1', 'on-accent', 'accent', 's:bold')}
${hi('User2', 'on-secondary', 'secondary', 's:bold')}
${hi('User3', 'on-success', 'success', 's:bold')}
${hi('User4', 'on-success', 'success')}
${hi('User5', 'on-warning', 'warning', 's:bold')}
${hi('User6', 'on-error', 'error', 's:bold')}
${hi('User7', isDark ? 'text' : 'on-accent', isDark ? 'accent-subtle' : 'accent', 's:bold')}
${hi('User8', 'text', isDark ? 'accent-subtle' : 'surface')}
${hi('User9', 'text-muted', isDark ? 'accent-subtle' : 'surface')}

${hi('Title', 'accent', null, 's:bold')}
${hi('Directory', 'accent', null, 's:bold')}

${hi('ErrorMsg', 'on-error', 'error', 's:bold')}
${hi('WarningMsg', 'on-warning', 'warning', 's:bold')}
${hi('ModeMsg', 'accent', null, 's:bold')}
${hi('MoreMsg', 'success', null, 's:bold')}
${hi('Question', 'secondary', null, 's:bold')}

${hi('NonText', 'border')}
${hi('SpecialKey', 'text-muted')}
${hi('Whitespace', 'border')}

" }}}
" Cursor: {{{

${hi('Cursor', null, null, 's:inverse')}
${link('lCursor', 'Cursor')}
${link('iCursor', 'Cursor')}
${link('vCursor', 'Cursor')}
${hi('TermCursor', 'accent', null, 's:inverse')}
${hi('TermCursorNC', 'text-muted', null, 's:inverse')}

" }}}
" Completion Menu: {{{

${hi('Pmenu', 'text', 'surface')}
${hi('PmenuSel', 'on-accent', 'accent', 's:bold')}
${hi('PmenuSbar', null, 'surface')}
${hi('PmenuThumb', null, 'border-strong')}

" }}}
" Diffs: {{{

${hi('DiffAdd', 'success', 'bg', 's:inverse')}
${hi('DiffChange', 'warning', 'bg', 's:inverse')}
${hi('DiffDelete', 'error', 'bg', 's:inverse')}
${hi('DiffText', 'accent', 'bg', 's:inverse')}

" }}}
" Spelling: {{{

if has("spell")
  ${hi('SpellBad', null, null, 's:undercurl')}
  ${hi('SpellCap', null, null, 's:undercurl')}
  ${hi('SpellLocal', null, null, 's:undercurl')}
  ${hi('SpellRare', null, null, 's:undercurl')}
endif

" }}}
" }}}
" Syntax Highlighting: {{{

${hi('Comment', 'text-muted', null, 's:italic_comments')}
${hi('Todo', 'on-accent', 'accent', 's:bold')}
${hi('Error', 'on-error', 'error', 's:bold')}

" Generic statement
${hi('Statement', 'syntax-keyword', null, 's:bold')}
${hi('Conditional', 'syntax-keyword')}
${hi('Repeat', 'syntax-keyword')}
${hi('Label', 'syntax-keyword')}
${hi('Exception', 'error', null, 's:bold')}
${hi('Operator', 'text')}
${hi('Keyword', 'syntax-keyword', null, 's:bold')}

" Variable name
${hi('Identifier', 'text')}
${hi('Function', 'syntax-func', null, 's:bold')}

" Generic preprocessor
${hi('PreProc', 'syntax-type')}
${hi('Include', 'syntax-type')}
${hi('Define', 'syntax-type')}
${hi('Macro', 'syntax-type')}
${hi('PreCondit', 'syntax-type')}

" Generic constant
${hi('Constant', 'syntax-const')}
${hi('Character', 'syntax-const')}
${hi('String', 'syntax-string', null, 's:italic_strings')}
${hi('Boolean', 'syntax-const')}
${hi('Number', 'syntax-const')}
${hi('Float', 'syntax-const')}

" Generic type
${hi('Type', 'syntax-type', null, 's:bold')}
${hi('StorageClass', 'syntax-keyword')}
${hi('Structure', 'syntax-type')}
${hi('Typedef', 'syntax-type')}

" Generic special
${hi('Special', 'secondary')}
${hi('SpecialChar', 'secondary')}
${hi('Tag', 'accent')}
${hi('Delimiter', 'text-subtle')}
${hi('SpecialComment', 'text-subtle', null, 's:italic')}
${hi('Debug', 'error')}

${hi('Underlined', 'link', null, 's:underline')}
${hi('Ignore', 'text-muted')}

" }}}
" Plugin Support: {{{
" Statusline Plugins: {{{
" Support for Airline, Lightline, and Lualine
"
" Main segments (Mode, Filename, Info)
" Mode indicator (Normal/Insert/etc.)
${hi('Airlinea', 'on-accent', 'accent', 's:bold')}
${hi('Airlinez', 'on-accent', 'accent', 's:bold')}

" Secondary segments (Branch, Filetype)
${hi('Airlineb', 'text', isDark ? 'accent-subtle' : 'surface')}
${hi('Airliney', 'text', isDark ? 'accent-subtle' : 'surface')}

" Middle segment (Filename)
${hi('Airlinec', 'text', 'bg')}

" Inactive statusline
${hi('Airlinea_inactive', 'text-muted', 'surface')}
${hi('Airlineb_inactive', 'text-muted', 'surface')}
${hi('Airlinec_inactive', 'text-muted', 'bg')}

" Lightline mappings
${hi('LightlineLeft_active_0', 'on-accent', 'accent', 's:bold')}
${hi('LightlineLeft_active_1', 'text', isDark ? 'accent-subtle' : 'surface')}
${hi('LightlineMiddle_active', 'text-subtle', 'bg')}
${hi('LightlineRight_active_0', 'on-accent', 'accent', 's:bold')}
${hi('LightlineRight_active_1', 'text', isDark ? 'accent-subtle' : 'surface')}

" }}}
" GitGutter: {{{

${link('GitGutterAdd', 'DiffAdd')}
${link('GitGutterChange', 'DiffChange')}
${link('GitGutterDelete', 'DiffDelete')}
${link('GitGutterChangeDelete', 'DiffChange')}

" }}}
" Signify: {{{

${link('SignifySignAdd', 'DiffAdd')}
${link('SignifySignChange', 'DiffChange')}
${link('SignifySignDelete', 'DiffDelete')}

" }}}
" ALE (Asynchronous Lint Engine): {{{

${hi('ALEError', null, null, 's:undercurl')}
${hi('ALEWarning', null, null, 's:undercurl')}
${hi('ALEInfo', null, null, 's:undercurl')}
${hi('ALEErrorSign', 'error', 'bg')}
${hi('ALEWarningSign', 'warning', 'bg')}
${hi('ALEInfoSign', 'info', 'bg')}

" }}}
" COC (Conquer of Completion): {{{

${hi('CocErrorSign', 'error', 'bg')}
${hi('CocWarningSign', 'warning', 'bg')}
${hi('CocInfoSign', 'info', 'bg')}
${hi('CocHintSign', 'accent', 'bg')}
${hi('CocErrorFloat', 'error')}
${hi('CocWarningFloat', 'warning')}
${hi('CocInfoFloat', 'info')}
${hi('CocHintFloat', 'accent')}
${hi('CocErrorHighlight', null, null, 's:undercurl')}
${hi('CocWarningHighlight', null, null, 's:undercurl')}
${hi('CocInfoHighlight', null, null, 's:undercurl')}
${hi('CocHintHighlight', null, null, 's:undercurl')}

" Neovim UI: {{{
" Floating Windows, Modern Separators, and Messages

${hi('NormalFloat', 'text', 'elevated')}
${hi('FloatBorder', 'border-strong', 'elevated')}
${hi('FloatTitle', 'accent', 'elevated', 's:bold')}
${hi('MsgArea', 'text', 'bg')}
${hi('MsgSeparator', 'divider', 'bg')}
${hi('WinSeparator', 'border', 'bg')}
${hi('Substitute', 'on-warning', 'warning', 's:bold')}
${hi('CurSearch', 'on-accent', 'accent', 's:bold')}
${hi('Question', 'secondary', null, 's:bold')}
${hi('QuickFixLine', null, 'accent-soft', 's:bold')}
${hi('WinBar', 'text', 'bg', 's:bold')}
${hi('WinBarNC', 'text-muted', 'bg')}

" }}}
" Neovim LSP: {{{

${hi('DiagnosticError', 'error')}
${hi('DiagnosticWarn', 'warning')}
${hi('DiagnosticInfo', 'info')}
${hi('DiagnosticHint', 'teal')}
${hi('DiagnosticOk', 'success')}

${hi('DiagnosticVirtualTextError', 'error', 'error-subtle')}
${hi('DiagnosticVirtualTextWarn', 'warning', 'warning-subtle')}
${hi('DiagnosticVirtualTextInfo', 'info', 'info-subtle')}
${hi('DiagnosticVirtualTextHint', 'teal', 'teal-subtle')}

${hi('DiagnosticUnderlineError', null, null, 's:undercurl')}
${hi('DiagnosticUnderlineWarn', null, null, 's:undercurl')}
${hi('DiagnosticUnderlineInfo', null, null, 's:undercurl')}
${hi('DiagnosticUnderlineHint', null, null, 's:undercurl')}

${hi('LspSignatureActiveParameter', 'accent', null, 's:bold')}
${hi('LspReferenceText', null, 'surface')}
${hi('LspReferenceRead', null, 'surface')}
${hi('LspReferenceWrite', null, 'surface')}

" }}}
" Neovim Treesitter: {{{
" Standard @capture links to existing Candi syntax groups
" Guarded for Neovim only as standard Vim doesn't support '@' in group names

if has('nvim')
${link('@variable', 'Identifier')}
${link('@variable.builtin', 'Identifier')}
${hi('@variable.parameter', 'syntax-var')}
${hi('@variable.member', 'secondary')}

${link('@function', 'Function')}
${link('@function.builtin', 'Function')}
${link('@function.call', 'Function')}
${link('@function.macro', 'Macro')}

${hi('@method', 'syntax-func', null, 's:bold')}
${hi('@method.call', 'syntax-func')}

${link('@keyword', 'Keyword')}
${link('@keyword.function', 'Keyword')}
${link('@keyword.return', 'Keyword')}
${link('@keyword.operator', 'Operator')}

${link('@type', 'Type')}
${link('@type.builtin', 'Type')}
${link('@type.definition', 'Type')}

${link('@constant', 'Constant')}
${link('@constant.builtin', 'Constant')}
${link('@constant.macro', 'Constant')}

${link('@string', 'String')}
${link('@string.regex', 'String')}
${link('@string.escape', 'Special')}

${link('@number', 'Number')}
${link('@boolean', 'Boolean')}
${link('@float', 'Float')}

${link('@property', 'Identifier')}
${hi('@field', 'secondary')}
${link('@constructor', 'Type')}

${hi('@attribute', 'accent')}
${link('@label', 'Label')}
${link('@operator', 'Operator')}
${link('@exception', 'Exception')}

${link('@comment', 'Comment')}
${link('@punctuation', 'Delimiter')}
${link('@punctuation.bracket', 'Delimiter')}
${link('@punctuation.delimiter', 'Delimiter')}

${link('@tag', 'Tag')}
${link('@tag.attribute', 'Identifier')}
${link('@tag.delimiter', 'Delimiter')}
endif

" }}}
" Modern Plugins (Telescope, Gitsigns, etc.): {{{

" Gitsigns
${hi('GitSignsAdd', 'success', 'bg')}
${hi('GitSignsChange', 'warning', 'bg')}
${hi('GitSignsDelete', 'error', 'bg')}

" Telescope
${hi('TelescopeBorder', 'border-strong')}
${hi('TelescopePromptBorder', 'accent')}
${hi('TelescopeResultsBorder', 'border')}
${hi('TelescopePreviewBorder', 'border')}
${hi('TelescopeMatching', 'accent', null, 's:bold')}
${hi('TelescopeSelection', 'text', 'surface', 's:bold')}

" Bufferline
${hi('BufferLineIndicatorSelected', 'accent')}
${hi('BufferLineFill', null, 'bg')}

" Nvim-Tree
${hi('NvimTreeRootFolder', 'accent', null, 's:bold')}
${hi('NvimTreeFolderName', 'accent')}
${hi('NvimTreeOpenedFolderName', 'accent', null, 's:italic')}
${hi('NvimTreeEmptyFolderName', 'text-muted')}
${hi('NvimTreeIndentMarker', 'border')}
${hi('NvimTreeVertSplit', 'border', 'bg')}

" }}}

" }}}
" NERDTree: {{{

${hi('NERDTreeDir', 'accent', null, 's:bold')}
${hi('NERDTreeDirSlash', 'accent')}
${hi('NERDTreeFile', 'text')}
${hi('NERDTreeExecFile', 'success', null, 's:bold')}
${hi('NERDTreeOpenable', 'secondary')}
${hi('NERDTreeClosable', 'secondary')}
${hi('NERDTreeUp', 'text-muted')}
${hi('NERDTreeCWD', 'accent', null, 's:bold')}

" }}}
" CtrlP: {{{

${hi('CtrlPMatch', 'accent', null, 's:bold')}
${hi('CtrlPNoEntries', 'error')}
${hi('CtrlPMode1', 'on-accent', 'accent', 's:bold')}
${hi('CtrlPMode2', 'text', 'surface', 's:bold')}

" }}}
" }}}
" Filetype Specific: {{{
" Markdown: {{{

${hi('markdownH1', 'accent', null, 's:bold')}
${hi('markdownH2', 'accent', null, 's:bold')}
${hi('markdownH3', 'secondary', null, 's:bold')}
${hi('markdownH4', 'secondary', null, 's:bold')}
${hi('markdownH5', 'secondary')}
${hi('markdownH6', 'secondary')}
${hi('markdownCode', 'syntax-string')}
${hi('markdownCodeBlock', 'syntax-string')}
${hi('markdownCodeDelimiter', 'syntax-string')}
${hi('markdownBlockquote', 'text-subtle', null, 's:italic')}
${hi('markdownListMarker', 'accent')}
${hi('markdownOrderedListMarker', 'accent')}
${hi('markdownRule', 'border')}
${hi('markdownLinkText', 'link', null, 's:underline')}
${hi('markdownUrl', 'link')}
${link('markdownIdDeclaration', 'markdownLinkText')}

" }}}
" HTML: {{{

${hi('htmlTag', 'text-subtle')}
${hi('htmlEndTag', 'text-subtle')}
${hi('htmlTagName', 'accent', null, 's:bold')}
${hi('htmlArg', 'secondary')}
${hi('htmlSpecialChar', 'syntax-const')}
${hi('htmlLink', 'link', null, 's:underline')}
${hi('htmlBold', null, null, 's:bold')}
${hi('htmlItalic', null, null, 's:italic')}

" }}}
" CSS: {{{

${hi('cssBraces', 'text-subtle')}
${hi('cssFunctionName', 'syntax-func')}
${hi('cssIdentifier', 'accent')}
${hi('cssClassName', 'accent')}
${hi('cssColor', 'syntax-const')}
${hi('cssImportant', 'error', null, 's:bold')}
${hi('cssProp', 'text')}

" }}}
" JavaScript: {{{

${hi('javaScriptBraces', 'text-subtle')}
${hi('javaScriptFunction', 'syntax-keyword', null, 's:bold')}
${hi('javaScriptIdentifier', 'syntax-keyword')}
${hi('javaScriptNumber', 'syntax-const')}
${hi('javaScriptNull', 'syntax-const')}

" }}}
" Python: {{{

${hi('pythonBuiltin', 'syntax-func')}
${hi('pythonFunction', 'syntax-func', null, 's:bold')}
${hi('pythonDecorator', 'secondary')}
${hi('pythonInclude', 'syntax-keyword')}
${hi('pythonOperator', 'syntax-keyword')}
${hi('pythonException', 'error', null, 's:bold')}

" }}}
" JSON: {{{

${hi('jsonKeyword', 'accent')}
${hi('jsonQuote', 'text-subtle')}
${hi('jsonBraces', 'text-subtle')}
${hi('jsonString', 'syntax-string')}

" }}}
" Vim: {{{

${hi('vimCommentTitle', 'text-subtle', null, 's:bold')}
${hi('vimNotation', 'secondary')}
${hi('vimBracket', 'secondary')}
${hi('vimMapModKey', 'secondary')}
${hi('vimCommand', 'syntax-keyword', null, 's:bold')}

" }}}
" }}}
" Rainbow Brackets: {{{
" Used by rainbow parentheses plugins (luochen1990/rainbow, p00f/nvim-ts-rainbow, etc.)

${hi('rainbowcol1', 'blue')}
${hi('rainbowcol2', 'magenta')}
${hi('rainbowcol3', 'cyan')}
${hi('rainbowcol4', 'yellow')}
${hi('rainbowcol5', 'green')}
${hi('rainbowcol6', 'red')}
${hi('rainbowcol7', 'gold')}

" Treesitter rainbow (nvim-ts-rainbow2, rainbow-delimiters.nvim)
${link('TSRainbowRed', 'rainbowcol6')}
${link('TSRainbowYellow', 'rainbowcol4')}
${link('TSRainbowBlue', 'rainbowcol1')}
${link('TSRainbowGreen', 'rainbowcol5')}
${link('TSRainbowViolet', 'rainbowcol2')}
${link('TSRainbowCyan', 'rainbowcol3')}
${link('TSRainbowOrange', 'rainbowcol7')}

" rainbow-delimiters.nvim
${link('RainbowDelimiterRed', 'rainbowcol6')}
${link('RainbowDelimiterYellow', 'rainbowcol4')}
${link('RainbowDelimiterBlue', 'rainbowcol1')}
${link('RainbowDelimiterGreen', 'rainbowcol5')}
${link('RainbowDelimiterViolet', 'rainbowcol2')}
${link('RainbowDelimiterCyan', 'rainbowcol3')}
${link('RainbowDelimiterOrange', 'rainbowcol7')}

" }}}
" Primitive Color Definitions: {{{
" Direct access to primitive colors for user customization

${hi('CandiRed', 'red')}
${hi('CandiRedSubtle', 'red-subtle')}
${hi('CandiRedStrong', 'red-strong')}
${hi('CandiOnRed', 'on-red')}
${hi('CandiBlue', 'blue')}
${hi('CandiBlueSubtle', 'blue-subtle')}
${hi('CandiBlueStrong', 'blue-strong')}
${hi('CandiOnBlue', 'on-blue')}
${hi('CandiGreen', 'green')}
${hi('CandiGreenSubtle', 'green-subtle')}
${hi('CandiGreenStrong', 'green-strong')}
${hi('CandiOnGreen', 'on-green')}
${hi('CandiYellow', 'yellow')}
${hi('CandiYellowSubtle', 'yellow-subtle')}
${hi('CandiYellowStrong', 'yellow-strong')}
${hi('CandiOnYellow', 'on-yellow')}
${hi('CandiMagenta', 'magenta')}
${hi('CandiMagentaSubtle', 'magenta-subtle')}
${hi('CandiMagentaStrong', 'magenta-strong')}
${hi('CandiOnMagenta', 'on-magenta')}
${hi('CandiCyan', 'cyan')}
${hi('CandiCyanSubtle', 'cyan-subtle')}
${hi('CandiCyanStrong', 'cyan-strong')}
${hi('CandiOnCyan', 'on-cyan')}
${hi('CandiTeal', 'teal')}
${hi('CandiTealSubtle', 'teal-subtle')}
${hi('CandiTealStrong', 'teal-strong')}
${hi('CandiOnTeal', 'on-teal')}
${hi('CandiPink', 'pink')}
${hi('CandiPinkSubtle', 'pink-subtle')}
${hi('CandiPinkStrong', 'pink-strong')}
${hi('CandiOnPink', 'on-pink')}
${hi('CandiGold', 'gold')}
${hi('CandiGoldSubtle', 'gold-subtle')}
${hi('CandiGoldStrong', 'gold-strong')}
${hi('CandiOnGold', 'on-gold')}
${hi('CandiSilver', 'silver')}
${hi('CandiSilverSubtle', 'silver-subtle')}
${hi('CandiSilverStrong', 'silver-strong')}
${hi('CandiOnSilver', 'on-silver')}

" }}}

" vim: set sw=2 ts=2 sts=2 et tw=80 ft=vim fdm=marker:
`;
}

// Ensure directories exist
if (!fs.existsSync(vimDir)) fs.mkdirSync(vimDir);
if (!fs.existsSync(colorsDir)) fs.mkdirSync(colorsDir);

// Get last modified dates from existing files
const lightThemePath = path.join(colorsDir, 'candi-light.vim');
const darkThemePath = path.join(colorsDir, 'candi-dark.vim');
const lightLastModified = getLastModifiedDate(lightThemePath);
const darkLastModified = getLastModifiedDate(darkThemePath);

// Generate themes with preserved last modified dates
const lightTheme = generateVimTheme('Light', 'light', lightColors, lightLastModified);
const darkTheme = generateVimTheme('Dark', 'dark', darkColors, darkLastModified);

// Only write if content has changed (excluding the Last Modified line)
const shouldWrite = (filePath, newContent) => {
    if (!fs.existsSync(filePath)) return true;

    const existingContent = fs.readFileSync(filePath, 'utf8');
    const stripDate = (content) => content.replace(/Last Modified: \d{4}-\d{2}-\d{2}/, 'Last Modified: XXXX-XX-XX');

    return stripDate(existingContent) !== stripDate(newContent);
};

// Write light theme
if (shouldWrite(lightThemePath, lightTheme)) {
    // Update the last modified date only if content changed
    const updatedLightTheme = lightTheme.replace(
        /Last Modified: \d{4}-\d{2}-\d{2}/,
        `Last Modified: ${new Date().toISOString().split('T')[0]}`
    );
    fs.writeFileSync(lightThemePath, updatedLightTheme);
    console.log('  - Updated vim/colors/candi-light.vim');
} else {
    if (logger.isVerbose) {
        console.log('  - vim/colors/candi-light.vim unchanged');
    }
}

// Write dark theme
if (shouldWrite(darkThemePath, darkTheme)) {
    // Update the last modified date only if content changed
    const updatedDarkTheme = darkTheme.replace(
        /Last Modified: \d{4}-\d{2}-\d{2}/,
        `Last Modified: ${new Date().toISOString().split('T')[0]}`
    );
    fs.writeFileSync(darkThemePath, updatedDarkTheme);
    logger.log('  - Updated vim/colors/candi-dark.vim');
} else {
    if (logger.isVerbose) {
        logger.log('  - vim/colors/candi-dark.vim unchanged');
    }
}

logger.log('Build complete!');
if (logger.isVerbose) {
    logger.log('Vim build successful.');
}
