const fs = require('fs');
const path = require('path');
const palette = require('../src/data/colors');

const kdeDir = path.join(__dirname, '..', 'kde');
const v4Dir = path.join(kdeDir, 'v4');
const v5Dir = path.join(kdeDir, 'v5');

const { parseOklch } = require('./color-conv');

const toKebab = (str) => str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

function getColors(mode) {
    const colors = {};
    for (const [key, data] of Object.entries(palette[mode])) {
        const value = data.oklch || data.value;
        const parsed = parseOklch(value);
        if (parsed) colors[toKebab(key)] = { r: parsed.r, g: parsed.g, b: parsed.b };
    }
    return colors;
}


const lightColors = getColors('light');
const darkColors = getColors('dark');

/**
 * Format RGB values for KDE color scheme (R,G,B)
 */
function formatRgb(color) {
    return `${color.r},${color.g},${color.b}`;
}

/**
 * Validate that all required color palette keys exist
 */
function validatePalette(palette, themeName) {
    const requiredKeys = [
        'bg',
        'surface',
        'elevated',
        'text',
        'text-subtle',
        'text-muted',
        'border',
        'accent',
        'accent-subtle',
        'secondary',
        'success',
        'warning',
        'error',
        'link',
        'disabled'
    ];

    const missingKeys = requiredKeys.filter(key => !palette[key]);

    if (missingKeys.length > 0) {
        console.error(`\x1b[31mError: Missing required color keys in ${themeName} palette:\x1b[0m`);
        missingKeys.forEach(key => {
            console.error(`  - --candi-${key}`);
        });
        console.error('\nPlease ensure all required color variables are defined in src/css/base.css');
        process.exit(1);
    }

    // Warn about any undefined RGB values
    requiredKeys.forEach(key => {
        const color = palette[key];
        if (color && (color.r === undefined || color.g === undefined || color.b === undefined)) {
            console.warn(`\x1b[33mWarning: Color '${key}' has undefined RGB values\x1b[0m`);
        }
    });
}


function generateKdeTheme(name, background, palette) {
    // KDE uses specific color roles for different UI elements
    const bgNormal = formatRgb(palette['bg']);
    const surface = formatRgb(palette['surface']);
    const elevated = formatRgb(palette['elevated']);
    const text = formatRgb(palette['text']);
    const textSubtle = formatRgb(palette['text-subtle']);
    const textMuted = formatRgb(palette['text-muted']);
    const border = formatRgb(palette['border']);
    const accent = formatRgb(palette['accent']);
    const accentSubtle = formatRgb(palette['accent-subtle']);
    const secondary = formatRgb(palette['secondary']);
    const success = formatRgb(palette['success']);
    const warning = formatRgb(palette['warning']);
    const error = formatRgb(palette['error']);
    const link = formatRgb(palette['link']);
    const disabled = formatRgb(palette['disabled']);

    // Primitive colors for custom theming
    const red = formatRgb(palette['red'] || palette['error']);
    const blue = formatRgb(palette['blue'] || palette['accent']);
    const green = formatRgb(palette['green'] || palette['success']);
    const yellow = formatRgb(palette['yellow'] || palette['warning']);
    const magenta = formatRgb(palette['magenta'] || palette['secondary']);
    const cyan = formatRgb(palette['cyan'] || palette['accent']);
    const teal = formatRgb(palette['teal'] || palette['accent']);
    const pink = formatRgb(palette['pink'] || palette['secondary']);
    const gold = formatRgb(palette['gold'] || palette['warning']);
    const silver = formatRgb(palette['silver'] || palette['text-muted']);

    return `# =============================================================================
# DO NOT EDIT THIS FILE DIRECTLY
# This file is auto-generated by scripts/build-kde.js
# Edit the source at src/data/colors.js and run: npm run build:kde
# =============================================================================

[General]
ColorScheme=Candi ${name}
Name=Candi ${name}

[Colors:Window]
BackgroundNormal=${bgNormal}
BackgroundAlternate=${surface}
ForegroundNormal=${text}
ForegroundInactive=${textMuted}
ForegroundActive=${accent}
ForegroundLink=${link}
ForegroundVisited=${secondary}
ForegroundNegative=${error}
ForegroundNeutral=${warning}
ForegroundPositive=${success}
DecorationFocus=${accent}
DecorationHover=${accentSubtle}

[Colors:Button]
BackgroundNormal=${elevated}
BackgroundAlternate=${surface}
ForegroundNormal=${text}
ForegroundInactive=${textMuted}
ForegroundActive=${accent}
ForegroundLink=${link}
ForegroundVisited=${secondary}
ForegroundNegative=${error}
ForegroundNeutral=${warning}
ForegroundPositive=${success}
DecorationFocus=${accent}
DecorationHover=${accentSubtle}

[Colors:Selection]
BackgroundNormal=${accent}
BackgroundAlternate=${accentSubtle}
ForegroundNormal=${elevated}
ForegroundInactive=${textMuted}
ForegroundActive=${elevated}
ForegroundLink=${elevated}
ForegroundVisited=${surface}
ForegroundNegative=${error}
ForegroundNeutral=${warning}
ForegroundPositive=${success}
DecorationFocus=${accent}
DecorationHover=${accentSubtle}

[Colors:View]
BackgroundNormal=${elevated}
BackgroundAlternate=${surface}
ForegroundNormal=${text}
ForegroundInactive=${textMuted}
ForegroundActive=${accent}
ForegroundLink=${link}
ForegroundVisited=${secondary}
ForegroundNegative=${error}
ForegroundNeutral=${warning}
ForegroundPositive=${success}
DecorationFocus=${accent}
DecorationHover=${accentSubtle}

[Colors:Tooltip]
BackgroundNormal=${surface}
BackgroundAlternate=${bgNormal}
ForegroundNormal=${text}
ForegroundInactive=${textMuted}
ForegroundActive=${accent}
ForegroundLink=${link}
ForegroundVisited=${secondary}
ForegroundNegative=${error}
ForegroundNeutral=${warning}
ForegroundPositive=${success}
DecorationFocus=${accent}
DecorationHover=${accentSubtle}

[Colors:Complementary]
BackgroundNormal=${secondary}
BackgroundAlternate=${accentSubtle}
ForegroundNormal=${elevated}
ForegroundInactive=${textMuted}
ForegroundActive=${accent}
ForegroundLink=${link}
ForegroundVisited=${secondary}
ForegroundNegative=${error}
ForegroundNeutral=${warning}
ForegroundPositive=${success}
DecorationFocus=${accent}
DecorationHover=${accentSubtle}

[Colors:Header]
BackgroundNormal=${accent}
BackgroundAlternate=${accentSubtle}
ForegroundNormal=${elevated}
ForegroundInactive=${textMuted}
ForegroundActive=${elevated}
ForegroundLink=${elevated}
ForegroundVisited=${surface}
ForegroundNegative=${error}
ForegroundNeutral=${warning}
ForegroundPositive=${success}
DecorationFocus=${accent}
DecorationHover=${accentSubtle}

[WM]
activeBackground=${accent}
activeForeground=${elevated}
inactiveBackground=${surface}
inactiveForeground=${textMuted}
activeBlend=${accent}
inactiveBlend=${surface}

[Colors:Candi]
# Primitive colors for custom theming
Red=${red}
Blue=${blue}
Green=${green}
Yellow=${yellow}
Magenta=${magenta}
Cyan=${cyan}
Teal=${teal}
Pink=${pink}
Gold=${gold}
Silver=${silver}
`;
}

/**
 * Ensure directory exists with proper error handling
 */
function ensureDir(dirPath) {
    if (fs.existsSync(dirPath)) return;

    try {
        fs.mkdirSync(dirPath, { recursive: true });
    } catch (err) {
        let message = `Failed to create directory: ${dirPath}`;

        switch (err.code) {
            case 'EACCES':
                message += '\n  Cause: Permission denied. Check write permissions for the parent directory.';
                break;
            case 'ENOSPC':
                message += '\n  Cause: No space left on device. Free up disk space and try again.';
                break;
            case 'EROFS':
                message += '\n  Cause: Read-only file system. Cannot create directories here.';
                break;
            case 'ENOTDIR':
                message += '\n  Cause: A component of the path is not a directory.';
                break;
            default:
                message += `\n  Cause: ${err.message}`;
        }

        console.error(`\x1b[31mError: ${message}\x1b[0m`);
        process.exit(1);
    }
}

// Ensure directories exist
ensureDir(kdeDir);
ensureDir(v4Dir);
ensureDir(v5Dir);

// 2. Validate palettes before generating themes
validatePalette(lightColors, 'Light');
validatePalette(darkColors, 'Dark');

// 3. Generate Themes for both v4 and v5 (same format, different directories)
const lightTheme = generateKdeTheme('Light', 'light', lightColors);
const darkTheme = generateKdeTheme('Dark', 'dark', darkColors);

fs.writeFileSync(path.join(v4Dir, 'CandiLight.colors'), lightTheme);
fs.writeFileSync(path.join(v4Dir, 'CandiDark.colors'), darkTheme);
fs.writeFileSync(path.join(v5Dir, 'CandiLight.colors'), lightTheme);
fs.writeFileSync(path.join(v5Dir, 'CandiDark.colors'), darkTheme);

console.log('Build complete!');
console.log('  - Generated kde/v4/CandiLight.colors');
console.log('  - Generated kde/v4/CandiDark.colors');
console.log('  - Generated kde/v5/CandiLight.colors');
console.log('  - Generated kde/v5/CandiDark.colors');
